### ISSUE TITLE
Not able to connect through jdbc

### ISSUE THREAD

**Issue by ved1303** [jupyter/docker-stacks#1092]
HI there,

First of all thanks for creating such a useful docker image.
I am using pyspark. I have placed ojdbc driver at "\home\jovyan\work\" 

`jar_import = "\home\jovyan\work\ojdbc6.jar"`
`spark = SparkSession.builder.appName("EIMConnect").config(
    "oracle.jdbc.driver.OracleDriver", jar_import).getOrCreate()`
`incremental_df = spark.read.format("jdbc").option("url", "jdbc:oracle:thin:login_url").option("query", "SELECT * FROM TABLE WHERE ROWNUM <= 10000").load()`

But I am getting error showing ": java.sql.SQLException: No suitable driver"

Am I missing anything here?

`Py4JJavaErrorTraceback (most recent call last)
<ipython-input-45-32898c9e3e21> in <module>
----> 1 incremental_df = spark.read.format("jdbc").option("url", "jdbc:oracle:thin:login_url").option("query", "SELECT * FROM TABLE WHERE ROWNUM <= 10000").load()

/usr/local/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o330.load.
: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:105)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:104)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:32)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by romainx** [comment]
Hello @ved1303,

I think it's not related to this stack but more to Spark configuration. However here is some information that could help--not tested.

You need to define external jars, one of the way to do it is to use `spark-defaults.conf` in `$SPARK_HOME/conf/`. More on that in [Spark configuration manual](https://spark.apache.org/docs/latest/configuration.html). For example.

```bash
spark.driver.extraClassPath=\home\jovyan\work\ojdbc6.jar
# Maybe not required
# spark.executor.extraClassPath=\home\jovyan\work\ojdbc6.jar
```

See also [this post](https://stackoverflow.com/questions/29552799/spark-unable-to-find-jdbc-driver) on SO.

Hope it helps.
Best.

**Comment by romainx** [comment]
@ved1303 any news about this issue, without any feedback or additional information we cannot help you. In consequence I will close this issue soon.

Best.

**Comment by romainx** [comment]
@ved1303 I'm closing this issue. Feel free to open a new one if needed.
