### ISSUE TITLE
Permission denied when mounting jupyter data dir

### ISSUE THREAD

**Issue by jingw222** [jupyter/docker-stacks#1330]
**What docker image you are using?**

`jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
services:
  jupyter-server:
    build:
      context: ./jupyter_server/
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - RESTARTABLE=yes
      - GRANT_SUDO=yes
      - NB_UID=1000
      - NB_GID=100
    expose:
      - "8888"
    volumes:
      - ${WORK_DIR}:/home/jovyan/work 
      - ${HOME}/.jupyter:/home/jovyan/.jupyter
      - ${HOME}/.local/share/jupyter:/home/jovyan/.local/share/jupyter
```
Note that I did `fix-permissions "${HOME}" "${CONDA_DIR}"` at the end of the Dockerfile.

**What do you expect to happen?**

No error launching the notebook server.

**What actually happens?**
Got this permission error
```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 1841, in initialize
    super(ServerApp, self).initialize(argv=argv)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 229, in initialize
    self.migrate_config()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 155, in migrate_config
    migrate()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/migrate.py", line 245, in migrate
    with open(os.path.join(env['jupyter_config'], 'migrated'), 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter/migrated'
```

So basically I'd like to mount and persist jupyter data directories in the container to host. What's the canonical way to achieve this?

**Comment by jingw222** [comment]
Tried that but still got the same PermissionError
```
$ echo $(id -u):$(id -g)
$ 1000:1000
```
```
      - NB_UID=1000
      - NB_GID=1000
```

**Comment by mathbunnyru** [comment]
Could you try not to mount these 2 folders?
Or, create them from the user which is running Docker (1000:1000 in your case).

**Comment by jingw222** [comment]
It raises no issues without mounting these two folders. But I wouldn't be able to persist jupyter data in those directories, right? I have them created already on the host running Docker.

**Comment by mathbunnyru** [comment]
> But I wouldn't be able to persist jupyter data in those directories, right? 

The data is stored in `/home/jovyan` folder, these two folders are for cache files / configs.
Or, `/home/jovyan/work` is also fine.

> I have them created already on the host running Docker.

Yes, but one is `root:root`, another is `root: users`, that's why I asked to create them from the user which is running Docker ((1000:1000 in your case).

**Comment by mathbunnyru** [comment]
You're welcome. Closing this issue as resolved.
