### ISSUE TITLE
Trouble with permissions and mounting local dir

### ISSUE THREAD

**Issue by mcd0well** [jupyter/docker-stacks#175]
I'm trying to use the `-w` and `-v` flags in order to keep notebooks when the container is destroyed.

I was expecting something like this to work:
`michael@matlab:~/notebooks/spark$ docker run -v $PWD:/home/jovyan/work -w=/home/jovyan/work -p 8888:8888 --rm -it jupyter/all-spark-notebook` but I get a permission denied message when I try to create a new notebook in `/home/jovyan/work`.

After much trial and error I found that I can create notebooks in `/home/jovyan` but NOT in `/home/jovyan/work`

This would be all good and well, except the `-w` will not allow me to serve notebooks from `/home/jovyan`. Running `docker run -v $PWD:/home/jovyan/ -w=/home/jovyan/ -p 8888:8888 --rm -it jupyter/all-spark-notebook` produces the following trace:

michael@matlab:~/notebooks/spark$ docker run -v $PWD:/home/jovyan/ -w=/home/jovyan/ -p 8888:8888 --rm -it jupyter/all-spark-notebook
/opt/conda/lib/python3.5/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/jovyan' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
Traceback (most recent call last):
File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1017, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 169, in migrate_config
    migrate()
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter'

I'm fairly new to using docker containers so I may be missing something trivial. Any help would be much appreciated.

**Comment by parente** [comment]
Thanks for the report. The notebook server in the Docker container runs as user `jovian` with user ID `1000` by default. If you mount a host directory, you must make sure that user/user ID has write permissions in it.

For example, on your host run:

```
mkdir ~/spark/notebooks
chown 1000 ~/spark/notebooks
docker run -v $PWD:/home/jovyan/work -p 8888:8888 --rm -it jupyter/all-spark-notebook
```

**Comment by mcd0well** [comment]
This solved it. I knew it was likely something basic. Thanks!
