### ISSUE TITLE
[BUG] - ImportError: cannot import name 'secure_write' issue

### ISSUE THREAD

**Issue by johnfelipe** [jupyter/docker-stacks#1758]
### What docker image(s) are you using?

all-spark-notebook

### OS system and architecture running docker image

Ubuntu 20

### What Docker command are you running?

docker-compose up -d

this is my files:

https://gist.github.com/4027bf012734c0c13c5c80093beb92fa

https://gist.github.com/dbd89454c61e16d9f3b0682362130d01

https://gist.github.com/45079140e11aa72bb697b69799cdd809

```
Step 8/22 : RUN $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in b0ab6f391d49
Traceback (most recent call last):
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'
The command '/bin/bash -o pipefail -c $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1
ERROR: Service 'jupyter-notebook' failed to build : Build failed

```

### How to Reproduce the problem?

docker-compose up -d

```
Step 5/22 : ARG conda_env=python36
 ---> Using cache
 ---> 809c6d9d0725
Step 6/22 : ARG py_ver=3.6
 ---> Using cache
 ---> 1f822f79bc4c
Step 7/22 : RUN conda create --quiet --yes -p $CONDA_DIR/envs/$conda_env python=$py_ver ipython ipykernel &&     conda clean --all -f -y
 ---> Using cache
 ---> ba958a1ae05c
Step 8/22 : RUN $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in b0ab6f391d49
Traceback (most recent call last):
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/envs/python36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/opt/conda/envs/python36/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'
The command '/bin/bash -o pipefail -c $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1
ERROR: Service 'jupyter-notebook' failed to build : Build failed

```

### Actual behavior

```
ImportError: cannot import name 'secure_write'
The command '/bin/bash -o pipefail -c $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1
ERROR: Service 'jupyter-notebook' failed to build : Build failed
```

**Comment by mathbunnyru** [comment]
I see `opt/conda/envs/python36` in your logs.
Unfortunately, this means you're using an old python version which is already EOL.
I think the best thing to do is to start using more modern python.
https://endoflife.date/python

**Comment by johnfelipe** [comment]
Can u help me with versions for edit my files?

**Comment by mathbunnyru** [comment]
https://gist.github.com/johnfelipe/dbd89454c61e16d9f3b0682362130d01

```
ARG conda_env=python36
ARG py_ver=3.6
```

I think you should change these variables, rebuild everything and you should be fine.

**Comment by johnfelipe** [comment]
3.8?
Or
3.7...

**Comment by johnfelipe** [comment]
i select 3.7, but this is my issue now


```
Removing intermediate container da22e9f05403
 ---> 920181295283
Step 13/21 : WORKDIR /tmp
 ---> Running in b45e3d3a0d85
Removing intermediate container b45e3d3a0d85
 ---> 9b76bbd2e989
Step 14/21 : RUN wget -q https://archive.apache.org/dist/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz &&     tar xzf "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" -C /usr/local --owner root --group root --no-same-owner &&     rm "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz"
 ---> Running in 503234cd988b
The command '/bin/bash -o pipefail -c wget -q https://archive.apache.org/dist/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz &&     tar xzf "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" -C /usr/local --owner root --group root --no-same-owner &&     rm "spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz"' returned a non-zero code: 8
ERROR: Service 'jupyter-notebook' failed to build : Build failed

```

**Comment by johnfelipe** [comment]
solved

spark:3.3.0
