### ISSUE TITLE
[BUG] - Reporting to JupyterHub fails with "RuntimeError: can't start new thread"

### ISSUE THREAD

**Issue by twalcari** [jupyter/docker-stacks#1767]
### What docker image(s) are you using?

base-notebook

### OS system and architecture running docker image

Tested on both Ubuntu 18.04 and Ubuntu 22.04

### What Docker command are you running?

*Image:* jupyter/base-notebook:0fd03d9356de
*Command:* start-notebook.sh --notebook-dir=/ --SingleUserNotebookApp.default_url='/lab/tree/project_antwerp'
*User*: root
*Environment:* 
GRANT_SUDO = yes
JPY_API_TOKEN = 9f42086c639d4bb1816e56b9a721010e
JUPYTERHUB_ACTIVITY_URL = http://193.191.148.147:19998/hub/api/users/twalcari@ilabt.imec.be/activity
JUPYTERHUB_ADMIN_ACCESS = 1
JUPYTERHUB_API_TOKEN = 9f42086c639d4bb1816e56b9a721010e
JUPYTERHUB_API_URL = http://193.191.148.147:19998/hub/api
JUPYTERHUB_BASE_URL = /
JUPYTERHUB_CLIENT_ID = jupyterhub-user-twalcari%40ilabt.imec.be
JUPYTERHUB_HOST =
JUPYTERHUB_OAUTH_CALLBACK_URL = /user/twalcari@ilabt.imec.be/oauth_callback
JUPYTERHUB_OAUTH_SCOPES = ["access:servers!server=twalcari@ilabt.imec.be/", "access:servers!user=twalcari@ilabt.imec.be"]
JUPYTERHUB_ROOT_DIR = /
JUPYTERHUB_SERVER_NAME =
JUPYTERHUB_SERVICE_PREFIX = /user/twalcari@ilabt.imec.be/
JUPYTERHUB_SERVICE_URL = http://127.0.0.1:0/user/twalcari@ilabt.imec.be/
JUPYTERHUB_USER = twalcari@ilabt.imec.be
JUPYTER_ENABLE_LAB = 1
LANG = en_US.UTF-8
NB_PROJECT = masked
NB_UMASK = 002
NB_USER = twalcari

### How to Reproduce the problem?

1. Start base-notebook via a JupyterHub instance
2. Wait for a few minutes after the notebook has started running
3. Because the Jupyter instance cannot report its status to JupyterHub, the Hub will abort the instance.

### Command output

```bash session
[E 2022-08-09 12:38:26.023 SingleUserLabApp mixins:490] Failed to connect to my Hub at http://193.191.148.147:19998/hub/api (attempt 5/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyterhub/singleuser/mixins.py", line 488, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.10/site-packages/tornado/simple_httpclient.py", line 338, in run
        stream = await self.tcp_client.connect(
      File "/opt/conda/lib/python3.10/site-packages/tornado/tcpclient.py", line 265, in connect
        addrinfo = await self.resolver.resolve(host, port, af)
      File "/opt/conda/lib/python3.10/site-packages/tornado/netutil.py", line 398, in resolve
        result = await IOLoop.current().run_in_executor(
      File "/opt/conda/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 257, in run_in_executor
        return self.asyncio_loop.run_in_executor(executor, func, *args)
      File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
        executor.submit(func, *args), loop=self)
      File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
        self._adjust_thread_count()
      File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
        t.start()
      File "/opt/conda/lib/python3.10/threading.py", line 935, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
```

### Expected behavior

Jupyter instance reporting its status to JupyterHub

### Actual behavior

Reporting fails due to `RuntimeError: can't start new thread`

### Anything else?

First version with this issue: [0fd03d9356de](https://hub.docker.com/layers/tensorflow-notebook/jupyter/tensorflow-notebook/0fd03d9356de/images/sha256-e741723980d1f7c01d264dc489622fdd965e892cc064b2c397d7a78f33daed56?context=explore)

Last version without this issue: [180033e2e6cf](https://hub.docker.com/layers/tensorflow-notebook/jupyter/tensorflow-notebook/180033e2e6cf/images/sha256-b62939e2279963d17f3cc1a874cf74590f42a06c109c9913da5d2375364ef75f?context=explore)

This seems related to the migration from Ubuntu 20.04 to 22.04 as base layer?

**Comment by twalcari** [comment]
Apparently, this was caused by an older version of Docker running on the node on which this container was deployed. More info: https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921
