### ISSUE TITLE
[BUG] - conda error while building base-notebook

### ISSUE THREAD

**Issue by djangoliv** [jupyter/docker-stacks#1810]
### What docker image(s) are you using?

base-notebook

### OS system and architecture running docker image

Debian bulseye

### What Docker command are you running?

docker build --build-arg PYTHON_VERSION=3.8 -t base-notebook:3.8  https://github.com/jupyter/docker-stacks.git#main:base-notebook --no-cache

### How to Reproduce the problem?

I used to build the the base-notebook image like this:

docker build --build-arg PYTHON_VERSION=3.8 -t base-notebook:3.8  https://github.com/jupyter/docker-stacks.git#main:base-notebook --no-cache

For some time this command ended with an error.

### Command output

```bash session
Step 21/32 : WORKDIR /tmp
 ---> Running in 9315df6f6a5a
Removing intermediate container 9315df6f6a5a
 ---> 5fe39406184f
Step 22/32 : RUN set -x &&     arch=$(uname -m) &&     if [ "${arch}" = "x86_64" ]; then         arch="64";     fi &&     wget -qO /tmp/micromamba.tar.bz2         "https://micromamba.snakepit.net/api/micromamba/linux-${arch}/latest" &&     tar -xvjf /tmp/micromamba.tar.bz2 --strip-components=1 bin/micromamba &&     rm /tmp/micromamba.tar.bz2 &&     PYTHON_SPECIFIER="python=${PYTHON_VERSION}" &&     if [[ "${PYTHON_VERSION}" == "default" ]]; then PYTHON_SPECIFIER="python"; fi &&     ./micromamba install         --root-prefix="${CONDA_DIR}"         --prefix="${CONDA_DIR}"         --yes         "${PYTHON_SPECIFIER}"         'mamba'         'notebook'         'jupyterhub'         'jupyterlab' &&     rm micromamba &&     mamba list python | grep '^python ' | tr -s ' ' | cut -d ' ' -f 1,2 >> "${CONDA_DIR}/conda-meta/pinned" &&     jupyter notebook --generate-config &&     mamba clean --all -f -y &&     npm cache clean --force &&     jupyter lab clean &&     rm -rf "/home/${NB_USER}/.cache/yarn" &&     fix-permissions "${CONDA_DIR}" &&     fix-permissions "/home/${NB_USER}"
 ---> Running in aa7ea1fd675a
++ uname -m
+ arch=x86_64
+ '[' x86_64 = x86_64 ']'
+ arch=64
+ wget -qO /tmp/micromamba.tar.bz2 https://micromamba.snakepit.net/api/micromamba/linux-64/latest
+ tar -xvjf /tmp/micromamba.tar.bz2 --strip-components=1 bin/micromamba
bin/micromamba
+ rm /tmp/micromamba.tar.bz2
+ PYTHON_SPECIFIER=python=3.8
+ [[ 3.8 == \d\e\f\a\u\l\t ]]
+ ./micromamba install --root-prefix=/opt/conda --prefix=/opt/conda --yes python=3.8 mamba notebook jupyterhub jupyterlab

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


Transaction

  Prefix: /opt/conda

  Updating specs:

   - python=3.8
   - mamba
   - notebook
   - jupyterhub
   - jupyterlab


  Package                               Version  Build               Channel                   Size
─────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                           0.1  conda_forge         conda-forge/linux-64       3kB
  + _openmp_mutex                           4.5  2_gnu               conda-forge/linux-64      24kB
  + alembic                               1.8.1  pyhd8ed1ab_0        conda-forge/noarch       140kB
  + anyio                                 3.6.2  pyhd8ed1ab_0        conda-forge/noarch        85kB
  + argon2-cffi                          21.3.0  pyhd8ed1ab_0        conda-forge/noarch        16kB
  + argon2-cffi-bindings                 21.2.0  py38h0a891b7_2      conda-forge/linux-64      35kB
  + asttokens                             2.0.8  pyhd8ed1ab_0        conda-forge/noarch        25kB
  + async_generator                        1.10  py_0                conda-forge/noarch        18kB
  + attrs                                22.1.0  pyh71513ae_1        conda-forge/noarch        49kB
  + babel                                2.10.3  pyhd8ed1ab_0        conda-forge/noarch         7MB
  + backcall                              0.2.0  pyh9f0ad1d_0        conda-forge/noarch        14kB
  + backports                               1.0  py_2                conda-forge/noarch         4kB
  + backports.functools_lru_cache         1.6.4  pyhd8ed1ab_0        conda-forge/noarch         9kB
  + beautifulsoup4                       4.11.1  pyha770c72_0        conda-forge/noarch        98kB
  + bleach                                5.0.1  pyhd8ed1ab_0        conda-forge/noarch       127kB
  + blinker                                 1.5  pyhd8ed1ab_0        conda-forge/noarch        15kB
  + brotlipy                              0.7.0  py38h0a891b7_1004   conda-forge/linux-64     350kB
  + bzip2                                 1.0.8  h7f98852_4          conda-forge/linux-64     496kB
  + c-ares                               1.18.1  h7f98852_0          conda-forge/linux-64     115kB
  + ca-certificates                   2022.9.24  ha878542_0          conda-forge/linux-64     154kB
  + certifi                           2022.9.24  pyhd8ed1ab_0        conda-forge/noarch       159kB
  + certipy                               0.1.3  py_0                conda-forge/noarch        17kB
  + cffi                                 1.15.1  py38h4a40e3a_1      conda-forge/linux-64     234kB
  + charset-normalizer                    2.1.1  pyhd8ed1ab_0        conda-forge/noarch        36kB
  + colorama                              0.4.5  pyhd8ed1ab_0        conda-forge/noarch        19kB
  + conda                                4.12.0  py38h578d9bd_0      conda-forge/linux-64       1MB
  + conda-package-handling                1.9.0  py38h0a891b7_0      conda-forge/linux-64       1MB
  + configurable-http-proxy               4.5.3  he2f69ee_3          conda-forge/linux-64       2MB
  + cryptography                         38.0.2  py38h80a4ca7_1      conda-forge/linux-64       2MB
  + debugpy                               1.6.3  py38hfa26641_0      conda-forge/linux-64       2MB
  + decorator                             5.1.1  pyhd8ed1ab_0        conda-forge/noarch        12kB
  + defusedxml                            0.7.1  pyhd8ed1ab_0        conda-forge/noarch        24kB
  + entrypoints                             0.4  pyhd8ed1ab_0        conda-forge/noarch         9kB
  + executing                             1.1.1  pyhd8ed1ab_0        conda-forge/noarch        24kB
  + flit-core                             3.7.1  pyhd8ed1ab_0        conda-forge/noarch        45kB
  + greenlet                              1.1.3  py38hfa26641_0      conda-forge/linux-64      94kB
  + icu                                    70.1  h27087fc_0          conda-forge/linux-64      14MB
  + idna                                    3.4  pyhd8ed1ab_0        conda-forge/noarch        57kB
  + importlib-metadata                   4.11.4  py38h578d9bd_0      conda-forge/linux-64      34kB
  + importlib_metadata                   4.11.4  hd8ed1ab_0          conda-forge/noarch         4kB
  + importlib_resources                  5.10.0  pyhd8ed1ab_0        conda-forge/noarch        30kB
  + ipykernel                            6.16.1  pyh210e3f2_0        conda-forge/noarch       102kB
  + ipython                               8.5.0  pyh41d4057_1        conda-forge/noarch       565kB
  + ipython_genutils                      0.2.0  py_1                conda-forge/noarch        22kB
  + jedi                                 0.18.1  pyhd8ed1ab_2        conda-forge/noarch       818kB
  + jinja2                                3.1.2  pyhd8ed1ab_1        conda-forge/noarch       101kB
  + json5                                 0.9.5  pyh9f0ad1d_0        conda-forge/noarch        21kB
  + jsonschema                           4.16.0  pyhd8ed1ab_0        conda-forge/noarch        66kB
  + jupyter_client                        7.4.3  pyhd8ed1ab_0        conda-forge/noarch        93kB
  + jupyter_core                         4.11.1  py38h578d9bd_0      conda-forge/linux-64      83kB
  + jupyter_server                       1.21.0  pyhd8ed1ab_0        conda-forge/noarch       244kB
  + jupyter_telemetry                     0.1.0  pyhd8ed1ab_1        conda-forge/noarch        10kB
  + jupyterhub                            3.0.0  pyhd8ed1ab_0        conda-forge/noarch         6kB
  + jupyterhub-base                       3.0.0  pyhd8ed1ab_0        conda-forge/noarch         2MB
  + jupyterlab                            3.5.0  pyhd8ed1ab_0        conda-forge/noarch         6MB
  + jupyterlab_pygments                   0.2.2  pyhd8ed1ab_0        conda-forge/noarch        17kB
  + jupyterlab_server                    2.16.1  pyhd8ed1ab_0        conda-forge/noarch        50kB
  + keyutils                              1.6.1  h166bdaf_0          conda-forge/linux-64     118kB
  + krb5                                 1.19.3  h08a2579_0          conda-forge/linux-64       2MB
  + ld_impl_linux-64                       2.39  hc81fddc_0          conda-forge/linux-64     778kB
  + libcurl                              7.85.0  h2283fc2_0          conda-forge/linux-64     359kB
  + libedit                        3.1.20191231  he28a2e2_2          conda-forge/linux-64     124kB
  + libev                                  4.33  h516909a_1          conda-forge/linux-64     106kB
  + libffi                                3.4.2  h7f98852_5          conda-forge/linux-64      58kB
  + libgcc-ng                            12.2.0  h65d4601_19         conda-forge/linux-64     954kB
  + libgomp                              12.2.0  h65d4601_19         conda-forge/linux-64     466kB
  + libnghttp2                           1.47.0  hff17c54_1          conda-forge/linux-64     844kB
  + libnsl                                2.0.0  h7f98852_0          conda-forge/linux-64      31kB
  + libsodium                            1.0.18  h36c2ea0_1          conda-forge/linux-64     375kB
  + libsolv                              0.7.22  h6239696_0          conda-forge/linux-64     454kB
  + libsqlite                            3.39.4  h753d276_0          conda-forge/linux-64     822kB
  + libssh2                              1.10.0  hf14f497_3          conda-forge/linux-64     239kB
  + libstdcxx-ng                         12.2.0  h46fd767_19         conda-forge/linux-64       4MB
  + libuuid                              2.32.1  h7f98852_1000       conda-forge/linux-64      28kB
  + libuv                                1.44.2  h166bdaf_0          conda-forge/linux-64       1MB
  + libzlib                              1.2.13  h166bdaf_4          conda-forge/linux-64      66kB
  + mako                                  1.2.3  pyhd8ed1ab_0        conda-forge/noarch        62kB
  + mamba                                 0.1.2  py38hbf85e49_0      conda-forge/linux-64     106kB
  + markupsafe                            2.1.1  py38h0a891b7_1      conda-forge/linux-64      23kB
  + matplotlib-inline                     0.1.6  pyhd8ed1ab_0        conda-forge/noarch        12kB
  + mistune                               2.0.4  pyhd8ed1ab_0        conda-forge/noarch        69kB
  + nbclassic                             0.4.5  pyhd8ed1ab_0        conda-forge/noarch         8MB
  + nbclient                              0.7.0  pyhd8ed1ab_0        conda-forge/noarch        67kB
  + nbconvert                             7.2.2  pyhd8ed1ab_0        conda-forge/noarch         6kB
  + nbconvert-core                        7.2.2  pyhd8ed1ab_0        conda-forge/noarch       193kB
  + nbconvert-pandoc                      7.2.2  pyhd8ed1ab_0        conda-forge/noarch         5kB
  + nbformat                              5.7.0  pyhd8ed1ab_0        conda-forge/noarch       109kB
  + ncurses                                 6.3  h27087fc_1          conda-forge/linux-64       1MB
  + nest-asyncio                          1.5.6  pyhd8ed1ab_0        conda-forge/noarch        10kB
  + nodejs                              18.11.0  h8839609_0          conda-forge/linux-64      17MB
  + notebook                              6.5.1  pyha770c72_0        conda-forge/noarch       273kB
  + notebook-shim                         0.2.0  pyhd8ed1ab_0        conda-forge/noarch        15kB
  + oauthlib                              3.2.2  pyhd8ed1ab_0        conda-forge/noarch        92kB
  + openssl                               3.0.5  h166bdaf_2          conda-forge/linux-64       3MB
  + packaging                              21.3  pyhd8ed1ab_0        conda-forge/noarch        36kB
  + pamela                                1.0.0  py_0                conda-forge/noarch         9kB
  + pandoc                               2.19.2  ha770c72_0          conda-forge/linux-64      13MB
  + pandocfilters                         1.5.0  pyhd8ed1ab_0        conda-forge/noarch        12kB
  + parso                                 0.8.3  pyhd8ed1ab_0        conda-forge/noarch        71kB
  + pexpect                               4.8.0  pyh9f0ad1d_2        conda-forge/noarch        48kB
  + pickleshare                           0.7.5  py_1003             conda-forge/noarch         9kB
  + pip                                    22.3  pyhd8ed1ab_0        conda-forge/noarch         2MB
  + pkgutil-resolve-name                 1.3.10  pyhd8ed1ab_0        conda-forge/noarch         9kB
  + prometheus_client                    0.15.0  pyhd8ed1ab_0        conda-forge/noarch        51kB
  + prompt-toolkit                       3.0.31  pyha770c72_0        conda-forge/noarch       260kB
  + psutil                                5.9.3  py38h0a891b7_0      conda-forge/linux-64     357kB
  + ptyprocess                            0.7.0  pyhd3deb0d_0        conda-forge/noarch        17kB
  + pure_eval                             0.2.2  pyhd8ed1ab_0        conda-forge/noarch        15kB
  + pycosat                               0.6.3  py38h0a891b7_1010   conda-forge/linux-64     110kB
  + pycparser                              2.21  pyhd8ed1ab_0        conda-forge/noarch       103kB
  + pycurl                               7.45.1  py38he9e1d38_2      conda-forge/linux-64      76kB
  + pygments                             2.13.0  pyhd8ed1ab_0        conda-forge/noarch       840kB
  + pyjwt                                 2.6.0  pyhd8ed1ab_0        conda-forge/noarch        21kB
  + pyopenssl                            22.1.0  pyhd8ed1ab_0        conda-forge/noarch       125kB
  + pyparsing                             3.0.9  pyhd8ed1ab_0        conda-forge/noarch        81kB
  + pyrsistent                           0.18.1  py38h0a891b7_1      conda-forge/linux-64      94kB
  + pysocks                               1.7.1  pyha2e5f31_6        conda-forge/noarch        19kB
  + python                               3.8.13  ha86cf86_0_cpython  conda-forge/linux-64      26MB
  + python-dateutil                       2.8.2  pyhd8ed1ab_0        conda-forge/noarch       246kB
  + python-fastjsonschema                2.16.2  pyhd8ed1ab_0        conda-forge/noarch       247kB
  + python-json-logger                    2.0.1  pyh9f0ad1d_0        conda-forge/noarch        10kB
  + python_abi                              3.8  2_cp38              conda-forge/linux-64       4kB
  + pytz                                 2022.5  pyhd8ed1ab_0        conda-forge/noarch       243kB
  + pyzmq                                24.0.1  py38hfc09fa9_0      conda-forge/linux-64     521kB
  + readline                              8.1.2  h0f457ee_0          conda-forge/linux-64     298kB
  + requests                             2.28.1  pyhd8ed1ab_1        conda-forge/noarch        55kB
  + ruamel.yaml                         0.17.21  py38h0a891b7_1      conda-forge/linux-64     176kB
  + ruamel.yaml.clib                      0.2.6  py38h0a891b7_1      conda-forge/linux-64     155kB
  + ruamel_yaml                         0.15.80  py38h0a891b7_1007   conda-forge/linux-64     270kB
  + send2trash                            1.8.0  pyhd8ed1ab_0        conda-forge/noarch        18kB
  + setuptools                           65.5.0  pyhd8ed1ab_0        conda-forge/noarch       787kB
  + six                                  1.16.0  pyh6c4a22f_0        conda-forge/noarch        14kB
  + sniffio                               1.3.0  pyhd8ed1ab_0        conda-forge/noarch        14kB
  + soupsieve                       2.3.2.post1  pyhd8ed1ab_0        conda-forge/noarch        35kB
  + sqlalchemy                           1.4.42  py38h0a891b7_0      conda-forge/linux-64       2MB
  + sqlite                               3.39.4  h4ff8645_0          conda-forge/linux-64     807kB
  + stack_data                            0.5.1  pyhd8ed1ab_0        conda-forge/noarch        25kB
  + terminado                            0.16.0  pyh41d4057_0        conda-forge/noarch        19kB
  + tinycss2                              1.2.1  pyhd8ed1ab_0        conda-forge/noarch        23kB
  + tk                                   8.6.12  h27826a3_0          conda-forge/linux-64       3MB
  + tomli                                 2.0.1  pyhd8ed1ab_0        conda-forge/noarch        16kB
  + tornado                                 6.2  py38h0a891b7_0      conda-forge/linux-64     669kB
  + tqdm                                 4.64.1  pyhd8ed1ab_0        conda-forge/noarch        83kB
  + traitlets                             5.5.0  pyhd8ed1ab_0        conda-forge/noarch        87kB
  + typing_extensions                     4.4.0  pyha770c72_0        conda-forge/noarch        30kB
  + urllib3                             1.26.11  pyhd8ed1ab_0        conda-forge/noarch       104kB
  + wcwidth                               0.2.5  pyh9f0ad1d_2        conda-forge/noarch        34kB
  + webencodings                          0.5.1  py_1                conda-forge/noarch        12kB
  + websocket-client                      1.4.1  pyhd8ed1ab_0        conda-forge/noarch        43kB
  + wheel                                0.37.1  pyhd8ed1ab_0        conda-forge/noarch        32kB
  + xz                                    5.2.6  h166bdaf_0          conda-forge/linux-64     418kB
  + yaml                                  0.2.5  h7f98852_2          conda-forge/linux-64      89kB
  + zeromq                                4.3.4  h9c3ff4c_1          conda-forge/linux-64     360kB
  + zipp                                  3.9.0  pyhd8ed1ab_0        conda-forge/noarch        14kB
  + zlib                                 1.2.13  h166bdaf_4          conda-forge/linux-64      94kB

  Summary:

  Install: 155 packages

  Total download: 140MB

─────────────────────────────────────────────────────────────────────────────────────────────────────


Transaction starting
Linking pandoc-2.19.2-ha770c72_0
Linking _libgcc_mutex-0.1-conda_forge
Linking libstdcxx-ng-12.2.0-h46fd767_19
Linking ld_impl_linux-64-2.39-hc81fddc_0
Linking ca-certificates-2022.9.24-ha878542_0
Linking libgomp-12.2.0-h65d4601_19
Linking _openmp_mutex-4.5-2_gnu
Linking libgcc-ng-12.2.0-h65d4601_19
Linking libuuid-2.32.1-h7f98852_1000
Linking libsodium-1.0.18-h36c2ea0_1
Linking libev-4.33-h516909a_1
Linking yaml-0.2.5-h7f98852_2
Linking libuv-1.44.2-h166bdaf_0
Linking icu-70.1-h27087fc_0
Linking c-ares-1.18.1-h7f98852_0
Linking keyutils-1.6.1-h166bdaf_0
Linking xz-5.2.6-h166bdaf_0
Linking openssl-3.0.5-h166bdaf_2
Linking ncurses-6.3-h27087fc_1
Linking libffi-3.4.2-h7f98852_5
Linking bzip2-1.0.8-h7f98852_4
Linking libzlib-1.2.13-h166bdaf_4
Linking libnsl-2.0.0-h7f98852_0
Linking zeromq-4.3.4-h9c3ff4c_1
Linking libedit-3.1.20191231-he28a2e2_2
Linking readline-8.1.2-h0f457ee_0
Linking zlib-1.2.13-h166bdaf_4
Linking libssh2-1.10.0-hf14f497_3
Linking libnghttp2-1.47.0-hff17c54_1
Linking libsolv-0.7.22-h6239696_0
Linking libsqlite-3.39.4-h753d276_0
Linking tk-8.6.12-h27826a3_0
Linking krb5-1.19.3-h08a2579_0
Linking nodejs-18.11.0-h8839609_0
Linking sqlite-3.39.4-h4ff8645_0
Linking libcurl-7.85.0-h2283fc2_0
Linking configurable-http-proxy-4.5.3-he2f69ee_3
Linking python-3.8.13-ha86cf86_0_cpython
Linking wheel-0.37.1-pyhd8ed1ab_0
Linking setuptools-65.5.0-pyhd8ed1ab_0
Linking pip-22.3-pyhd8ed1ab_0
Linking colorama-0.4.5-pyhd8ed1ab_0
Linking pysocks-1.7.1-pyha2e5f31_6
Linking backports-1.0-py_2
Linking pytz-2022.5-pyhd8ed1ab_0
Linking parso-0.8.3-pyhd8ed1ab_0
Linking json5-0.9.5-pyh9f0ad1d_0
Linking blinker-1.5-pyhd8ed1ab_0
Linking pyjwt-2.6.0-pyhd8ed1ab_0
Linking pyparsing-3.0.9-pyhd8ed1ab_0
Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
Linking certifi-2022.9.24-pyhd8ed1ab_0
Linking pure_eval-0.2.2-pyhd8ed1ab_0
Linking executing-1.1.1-pyhd8ed1ab_0
Linking ptyprocess-0.7.0-pyhd3deb0d_0
Linking pycparser-2.21-pyhd8ed1ab_0
Linking sniffio-1.3.0-pyhd8ed1ab_0
Linking idna-3.4-pyhd8ed1ab_0
Linking flit-core-3.7.1-pyhd8ed1ab_0
Linking soupsieve-2.3.2.post1-pyhd8ed1ab_0
Linking six-1.16.0-pyh6c4a22f_0
Linking zipp-3.9.0-pyhd8ed1ab_0
Linking backcall-0.2.0-pyh9f0ad1d_0
Linking pickleshare-0.7.5-py_1003
Linking decorator-5.1.1-pyhd8ed1ab_0
Linking attrs-22.1.0-pyh71513ae_1
Linking typing_extensions-4.4.0-pyha770c72_0
Linking websocket-client-1.4.1-pyhd8ed1ab_0
Linking python-json-logger-2.0.1-pyh9f0ad1d_0
Linking async_generator-1.10-py_0
Linking pamela-1.0.0-py_0
Linking tomli-2.0.1-pyhd8ed1ab_0
Linking nest-asyncio-1.5.6-pyhd8ed1ab_0
Linking pygments-2.13.0-pyhd8ed1ab_0
Linking mistune-2.0.4-pyhd8ed1ab_0
Linking pandocfilters-1.5.0-pyhd8ed1ab_0
Linking entrypoints-0.4-pyhd8ed1ab_0
Linking defusedxml-0.7.1-pyhd8ed1ab_0
Linking webencodings-0.5.1-py_1
Linking python-fastjsonschema-2.16.2-pyhd8ed1ab_0
Linking pkgutil-resolve-name-1.3.10-pyhd8ed1ab_0
Linking traitlets-5.5.0-pyhd8ed1ab_0
Linking prometheus_client-0.15.0-pyhd8ed1ab_0
Linking send2trash-1.8.0-pyhd8ed1ab_0
Linking ipython_genutils-0.2.0-py_1
Linking tqdm-4.64.1-pyhd8ed1ab_0
Linking backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
Linking babel-2.10.3-pyhd8ed1ab_0
Linking jedi-0.18.1-pyhd8ed1ab_2
Linking packaging-21.3-pyhd8ed1ab_0
Linking pexpect-4.8.0-pyh9f0ad1d_2
Linking beautifulsoup4-4.11.1-pyha770c72_0
Linking asttokens-2.0.8-pyhd8ed1ab_0
Linking python-dateutil-2.8.2-pyhd8ed1ab_0
Linking importlib_resources-5.10.0-pyhd8ed1ab_0
Linking anyio-3.6.2-pyhd8ed1ab_0
Linking jupyterlab_pygments-0.2.2-pyhd8ed1ab_0
Linking tinycss2-1.2.1-pyhd8ed1ab_0
Linking matplotlib-inline-0.1.6-pyhd8ed1ab_0
Linking wcwidth-0.2.5-pyh9f0ad1d_2
Linking bleach-5.0.1-pyhd8ed1ab_0
Linking stack_data-0.5.1-pyhd8ed1ab_0
Linking prompt-toolkit-3.0.31-pyha770c72_0
Linking ipython-8.5.0-pyh41d4057_1
Linking python_abi-3.8-2_cp38
Linking ruamel_yaml-0.15.80-py38h0a891b7_1007
Linking pycosat-0.6.3-py38h0a891b7_1010
Linking conda-package-handling-1.9.0-py38h0a891b7_0
Linking cffi-1.15.1-py38h4a40e3a_1
Linking pycurl-7.45.1-py38he9e1d38_2
Linking ruamel.yaml.clib-0.2.6-py38h0a891b7_1
Linking greenlet-1.1.3-py38hfa26641_0
Linking debugpy-1.6.3-py38hfa26641_0
Linking pyrsistent-0.18.1-py38h0a891b7_1
Linking psutil-5.9.3-py38h0a891b7_0
Linking markupsafe-2.1.1-py38h0a891b7_1
Linking importlib-metadata-4.11.4-py38h578d9bd_0
Linking pyzmq-24.0.1-py38hfc09fa9_0
Linking jupyter_core-4.11.1-py38h578d9bd_0
Linking tornado-6.2-py38h0a891b7_0
Linking brotlipy-0.7.0-py38h0a891b7_1004
Linking cryptography-38.0.2-py38h80a4ca7_1
Linking argon2-cffi-bindings-21.2.0-py38h0a891b7_2
Linking ruamel.yaml-0.17.21-py38h0a891b7_1
Linking sqlalchemy-1.4.42-py38h0a891b7_0
Linking jinja2-3.1.2-pyhd8ed1ab_1
Linking mako-1.2.3-pyhd8ed1ab_0
Linking jsonschema-4.16.0-pyhd8ed1ab_0
Linking importlib_metadata-4.11.4-hd8ed1ab_0
Linking terminado-0.16.0-pyh41d4057_0
Linking jupyter_client-7.4.3-pyhd8ed1ab_0
Linking pyopenssl-22.1.0-pyhd8ed1ab_0
Linking oauthlib-3.2.2-pyhd8ed1ab_0
Linking argon2-cffi-21.3.0-pyhd8ed1ab_0
Linking alembic-1.8.1-pyhd8ed1ab_0
Linking nbformat-5.7.0-pyhd8ed1ab_0
Linking jupyter_telemetry-0.1.0-pyhd8ed1ab_1
Linking ipykernel-6.16.1-pyh210e3f2_0
Linking urllib3-1.26.11-pyhd8ed1ab_0
Linking certipy-0.1.3-py_0
Linking nbclient-0.7.0-pyhd8ed1ab_0
Linking requests-2.28.1-pyhd8ed1ab_1
Linking nbconvert-core-7.2.2-pyhd8ed1ab_0
Linking jupyterhub-base-3.0.0-pyhd8ed1ab_0
Linking jupyter_server-1.21.0-pyhd8ed1ab_0
Linking nbconvert-pandoc-7.2.2-pyhd8ed1ab_0
Linking jupyterhub-3.0.0-pyhd8ed1ab_0
Linking jupyterlab_server-2.16.1-pyhd8ed1ab_0
Linking notebook-shim-0.2.0-pyhd8ed1ab_0
Linking nbconvert-7.2.2-pyhd8ed1ab_0
Linking nbclassic-0.4.5-pyhd8ed1ab_0
Linking notebook-6.5.1-pyha770c72_0
Linking jupyterlab-3.5.0-pyhd8ed1ab_0
Linking conda-4.12.0-py38h578d9bd_0
Linking mamba-0.1.2-py38hbf85e49_0
Transaction finished
+ rm micromamba
+ mamba list python
+ grep '^python '
+ tr -s ' '
+ cut -d ' ' -f 1,2
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/lib/python3.8/site-packages/mamba/mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "/opt/conda/lib/python3.8/site-packages/mamba/utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "/opt/conda/lib/python3.8/site-packages/mamba/FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
The command '/bin/bash -o pipefail -c set -x &&     arch=$(uname -m) &&     if [ "${arch}" = "x86_64" ]; then         arch="64";     fi &&     wget -qO /tmp/micromamba.tar.bz2         "https://micromamba.snakepit.net/api/micromamba/linux-${arch}/latest" &&     tar -xvjf /tmp/micromamba.tar.bz2 --strip-components=1 bin/micromamba &&     rm /tmp/micromamba.tar.bz2 &&     PYTHON_SPECIFIER="python=${PYTHON_VERSION}" &&     if [[ "${PYTHON_VERSION}" == "default" ]]; then PYTHON_SPECIFIER="python"; fi &&     ./micromamba install         --root-prefix="${CONDA_DIR}"         --prefix="${CONDA_DIR}"         --yes         "${PYTHON_SPECIFIER}"         'mamba'         'notebook'         'jupyterhub'         'jupyterlab' &&     rm micromamba &&     mamba list python | grep '^python ' | tr -s ' ' | cut -d ' ' -f 1,2 >> "${CONDA_DIR}/conda-meta/pinned" &&     jupyter notebook --generate-config &&     mamba clean --all -f -y &&     npm cache clean --force &&     jupyter lab clean &&     rm -rf "/home/${NB_USER}/.cache/yarn" &&     fix-permissions "${CONDA_DIR}" &&     fix-permissions "/home/${NB_USER}"' returned a non-zero code: 1
```

### Expected behavior

The build succed.

### Actual behavior

The build finish in error

### Anything else?

Regards

**Comment by mathbunnyru** [comment]
`Linking mamba-0.1.2-py38hbf85e49_0`
This is really old.
Could you please specify `"mamba>=0.27.0"` when running `micromamba install`?

**Comment by mathbunnyru** [comment]
Also, this issue is not specific to Docker stacks and should probably be asked in the upstream mamba project.
And it's not new.
https://github.com/mamba-org/mamba/issues/1583

**Comment by djangoliv** [comment]
With the command

`docker build --build-arg PYTHON_VERSION=3.8 -t base-notebook:3.8 https://github.com/jupyter/docker-stacks.git#main:base-notebook --no-cache`

I am using the base notebook Docker file: https://github.com/jupyter/docker-stacks/blob/main/base-notebook/Dockerfile

I'll try to upload the file to modify it, but I'm surprised you don't have the same problem.

Regards

**Comment by djangoliv** [comment]
I checked, the micromamba version is 0.27.0.

**Comment by jakirkham** [comment]
FWIW we did a new Miniforge release a couple days ago, which has the new `mamba`. So maybe that is an option?

https://github.com/conda-forge/miniforge/releases/tag/22.9.0-0

**Comment by mathbunnyru** [comment]
@jakirkham 
We've switched from Miniforge to micromamba, so I don't think we would like to switch back.
I've tried to build Dockerfile again, still see the same issue.

**Comment by jakirkham** [comment]
Yeah was poking around and noticed that.

Maybe it is worth [asking for a new micromamba release]( https://github.com/mamba-org/mamba/issues )?

**Comment by mathbunnyru** [comment]
@jakirkham was this issue fixed since the last release or why do you think this will help?

**Comment by jakirkham** [comment]
That is my understanding, yes. We've done updates in other places in conda-forge to pickup new `mamba` releases

Perhaps another option is just to grab `micromamba` from `conda-forge`. We [do that as part of some scripts]( https://github.com/conda-forge/miniforge/blob/2e25aec041a47d8f7e962f2dbc9a1ef2e501e3b0/scripts/build.sh#L42-L53 ) already

**Comment by jakirkham** [comment]
@charlesbluca, if you have bandwidth, would you be able to try a PR to Jupyter docker-stacks with the suggestion for upgrading `micromamba` above?

**Comment by mathbunnyru** [comment]
https://github.com/jupyter/docker-stacks/pull/1813#issuecomment-1300847574
