### ISSUE TITLE
[BUG] - RuntimeError: can't start new thread when accessing the jupyter server

### ISSUE THREAD

**Issue by LucasMaris** [jupyter/docker-stacks#1830]
### What docker image(s) are you using?

tensorflow-notebook

### OS system and architecture running docker image

Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-133-generic x86_64)

### What Docker command are you running?

sudo docker run -it --rm -p 4886:8888 -v "${PWD}":/home/jovyan/work --user root -e CHOWN_EXTRA="/home/jovyan/work" -e CHOWN_EXTRA_OPTS="-R" jupyter/tensorflow-notebook

(but I get the same errors with the shorter: sudo docker run -it --rm -p 4886:8888 jupyter/tensorflow-notebook)

### How to Reproduce the problem?

1. Access & reroute the remote machine that will launch the docker (ssh -L 4886:localhost:4886 user@remote)
2. Get latest docker image on the remote machine (sudo docker pull jupyter/tensorflow-notebook)
3. Run docker on the remote machine (sudo docker run -it --rm -p 4886:8888 jupyter/tensorflow-notebook)
4. Access jupyter notebook on the local machine (http://localhost:4886)
5. Copy/paste the access token given by the remote machine and hit 'Log in'

### Command output

```bash session
$ sudo docker run -it --rm -p 4886:8888 -v "${PWD}":/home/jovyan/work --user root -e CHOWN_EXTRA="/home/jovyan/work" -e CHOWN_EXTRA_OPTS="-R" jupyter/tensorflow-notebook
Entered start.sh with args: jupyter lab
Ensuring /home/jovyan/work is owned by 1000:100 (chown options: -R)
Running as jovyan: jupyter lab
Fail to get yarn configuration. /opt/conda/bin/node[23]: ../../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x7f3c06e41419 node::Abort() [/opt/conda/bin/../lib/libnode.so.108]
 2: 0x7f3c06e414ab  [/opt/conda/bin/../lib/libnode.so.108]
 3: 0x7f3c06eb732d node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/opt/conda/bin/../lib/libnode.so.108]
 4: 0x7f3c06eb7412 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/opt/conda/bin/../lib/libnode.so.108]
 5: 0x7f3c06e03377  [/opt/conda/bin/../lib/libnode.so.108]
 6: 0x7f3c06e03b9d node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [/opt/conda/bin/../lib/libnode.so.108]
 7: 0x7f3c06e03fc3 node::Start(int, char**) [/opt/conda/bin/../lib/libnode.so.108]
 8: 0x7f3c063dbd90  [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7f3c063dbe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
10: 0x55cb7c75007f  [/opt/conda/bin/node]

[I 2022-11-16 08:04:51.075 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-11-16 08:04:51.079 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-11-16 08:04:51.079 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-11-16 08:04:51.079 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-11-16 08:04:51.086 ServerApp] nbclassic | extension was successfully linked.
[I 2022-11-16 08:04:51.087 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-11-16 08:04:51.290 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-11-16 08:04:51.307 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-11-16 08:04:51.308 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
[I 2022-11-16 08:04:51.308 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-11-16 08:04:51.311 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-11-16 08:04:51.314 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-11-16 08:04:51.315 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-11-16 08:04:51.315 ServerApp] Jupyter Server 1.23.2 is running at:
[I 2022-11-16 08:04:51.315 ServerApp] http://7448a13fd2cd:8888/lab?token=f7b61d9978c1a8ba257322b68d6701a12489e07cd4593704
[I 2022-11-16 08:04:51.315 ServerApp]  or http://127.0.0.1:8888/lab?token=f7b61d9978c1a8ba257322b68d6701a12489e07cd4593704
[I 2022-11-16 08:04:51.315 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-11-16 08:04:51.318 ServerApp]

    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-22-open.html
    Or copy and paste one of these URLs:
        http://7448a13fd2cd:8888/lab?token=f7b61d9978c1a8ba257322b68d6701a12489e07cd4593704
     or http://127.0.0.1:8888/lab?token=f7b61d9978c1a8ba257322b68d6701a12489e07cd4593704
[I 2022-11-16 08:04:54.890 ServerApp] 302 GET / (172.17.0.1) 0.86ms
[W 2022-11-16 08:04:54.929 ServerApp] Clearing invalid/expired login cookie username-localhost-4886
[W 2022-11-16 08:04:54.929 LabApp] Clearing invalid/expired login cookie username-localhost-4886
[I 2022-11-16 08:04:54.930 LabApp] 302 GET /lab? (172.17.0.1) 2.24ms
[I 2022-11-16 08:04:55.161 ServerApp] 302 GET / (172.17.0.1) 0.42ms
[I 2022-11-16 08:04:55.169 LabApp] 302 GET /lab? (172.17.0.1) 0.64ms
[I 2022-11-16 08:05:01.318 ServerApp] 302 POST /login?next=%2Flab%3F (172.17.0.1) 2.07ms
[E 2022-11-16 08:05:02.985 ServerApp] Uncaught exception GET /lab/api/build?1668585902320 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:4886', method='GET', uri='/lab/api/build?1668585902320', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab/handlers/build_handler.py", line 131, in get
        data = yield self.builder.get_status()
      File "/opt/conda/lib/python3.10/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/conda/lib/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab/handlers/build_handler.py", line 42, in get_status
        messages = yield self._run_build_check(
      File "/opt/conda/lib/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
        conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
      File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
        self._adjust_thread_count()
      File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
        t.start()
      File "/opt/conda/lib/python3.10/threading.py", line 935, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
[W 2022-11-16 08:05:02.988 LabApp] wrote error: 'Unhandled error'
[E 2022-11-16 08:05:02.988 LabApp] {
      "Host": "localhost:4886",
      "Accept": "*/*",
      "Referer": "http://localhost:4886/lab?",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 OPR/91.0.4516.106 (Edition GX-CN)"
    }
[E 2022-11-16 08:05:02.988 LabApp] 500 GET /lab/api/build?1668585902320 (172.17.0.1) 3.43ms referer=http://localhost:4886/lab?
[E 2022-11-16 08:05:03.253 ServerApp] Uncaught exception GET /api/nbconvert?1668585902421 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:4886', method='GET', uri='/api/nbconvert?1668585902421', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 35, in get
        exporters = await run_sync(base.get_export_names)
      File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 918, in run_sync_in_worker_thread
        worker.start()
      File "/opt/conda/lib/python3.10/threading.py", line 935, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
[W 2022-11-16 08:05:03.254 ServerApp] wrote error: 'Unhandled error'
[E 2022-11-16 08:05:03.255 ServerApp] {
      "Host": "localhost:4886",
      "Accept": "*/*",
      "Referer": "http://localhost:4886/lab?",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 OPR/91.0.4516.106 (Edition GX-CN)"
    }
[E 2022-11-16 08:05:03.255 ServerApp] 500 GET /api/nbconvert?1668585902421 (172.17.0.1) 127.04ms referer=http://localhost:4886/lab?
[E 2022-11-16 08:05:03.255 ServerApp] Uncaught exception GET /api/nbconvert?1668585902424 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:4886', method='GET', uri='/api/nbconvert?1668585902424', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/nbconvert/handlers.py", line 35, in get
        exporters = await run_sync(base.get_export_names)
      File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 918, in run_sync_in_worker_thread
        worker.start()
      File "/opt/conda/lib/python3.10/threading.py", line 935, in start
        _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread
[W 2022-11-16 08:05:03.255 ServerApp] wrote error: 'Unhandled error'
[E 2022-11-16 08:05:03.256 ServerApp] {
      "Host": "localhost:4886",
      "Accept": "*/*",
      "Referer": "http://localhost:4886/lab?",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 OPR/91.0.4516.106 (Edition GX-CN)"
    }
[E 2022-11-16 08:05:03.256 ServerApp] 500 GET /api/nbconvert?1668585902424 (172.17.0.1) 127.55ms referer=http://localhost:4886/lab?
```

### Expected behavior

Please excuse me if I am completely mistaken in reporting this. As far as I understand, (1) the ports have been rerouted correctly, as I can access the jupyter notebook from the remote docker through my local machine, and (2) the permission issues as described in the [Troubleshooting common problems](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html) have been resolved. The browser environment is accessible on my local machine, and I expected it to be able to open a notebook at this point.

### Actual behavior

Once logged into the jupyter browser environment, there are 2 unexpected errors in the command's output, for which I was not able to find an explanation neither on here or on stackoverflow:
1. "Fail to get yarn configuration": I am not certain whether this is an error or a warning; either way, the docker goes ahead and launches the jupyter notebook.
2. "Uncaught exception GET -> conda -> RuntimeError: can't start new thread": This seems to be the major issue?

After the steps are executed, the jupyter browser environment can be accessed, but clicking on 'Notebook' yields a "Error Starting Kernel - Failed to fetch" inside the browser environment, and a "channel 3: open failed: connect failed: Connection refused" inside the command line environment.

### Anything else?

Again, I am terribly sorry if the issue is on my side. I've spent multiple hours trying to fix it and I don't know where else to look at this point.

**Comment by mathbunnyru** [comment]
Someone already had this issue. Could you please try updating your `Docker` version:
https://github.com/jupyter/docker-stacks/issues/1800#issuecomment-1272368486

**Comment by LucasMaris** [comment]
Thanks for pointing me to that! Docker is on version 20.10.7, and after trying to update to a more recent version for a couple hours now, it simply turns out [this is the most recent version compatible with Ubuntu 16.04 “Xenial”,](https://docs.docker.com/engine/release-notes/#20108) which is the server I am working with (and can't upgrade). No luck on getting this to work then? Is there any way I could run an older jupyter docker image instead?

**Comment by mathbunnyru** [comment]
> No luck on getting this to work then?

Ubuntu 16.04 has reached its EOL (now it has only security updates), that's why it's gonna be difficult for you to keep using this OS. So I highly recommend to upgrade.

> Is there any way I could run an older jupyter docker image instead?

Yes, that's easy - we don't delete old images from DockerHub, ever.
There is a date tag as well, and it's not difficult to search the images
https://hub.docker.com/r/jupyter/tensorflow-notebook/tags?page=1&ordering=last_updated&name=2021
