### ISSUE TITLE
[BUG] - scipy-notebook has old jupyter_server version < 2.0 - Jupyter Server Terminals fails to start

### ISSUE THREAD

**Issue by EnigmaCurry** [jupyter/docker-stacks#1851]
### What docker image(s) are you using?

scipy-notebook

### OS system and architecture running docker image

Ubuntu/amd64

### What Docker command are you running?

```
IMAGE=jupyter/scipy-notebook; docker pull ${IMAGE} ; docker run --rm -it ${IMAGE}
```

### How to Reproduce the problem?

 * docker pull jupyter/scipy-notebook 
 * docker run --rm -it jupyter/scipy-notebook

### Command output

```bash session
Using default tag: latest
latest: Pulling from jupyter/scipy-notebook
Digest: sha256:d04c1e21489cc8c5ee6fe03c5748cf77872ccd6bbaa1cd50cd54ac424b68378a
Status: Image is up to date for jupyter/scipy-notebook:latest
docker.io/jupyter/scipy-notebook:latest
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[W 2022-12-27 22:59:05.372 ServerApp] jupyter_server_terminals | error adding extension (enabled: True): Jupyter Server Terminals requires Jupyter Server 2.0+
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 166, in __init__
        super().__init__(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py", line 1360, in __init__
        value = self._traits[key]._cross_validate(self, getattr(self, key))
      File "/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py", line 746, in _cross_validate
        value = obj._trait_validators[self.name](obj, proposal)
      File "/opt/conda/lib/python3.10/site-packages/traitlets/traitlets.py", line 1232, in __call__
        return self.func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 175, in _validate_name
        self._module, self._metadata = get_metadata(name)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/utils.py", line 55, in get_metadata
        module = importlib.import_module(package_name)
      File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_terminals/__init__.py", line 9, in <module>
        raise RuntimeError("Jupyter Server Terminals requires Jupyter Server 2.0+")
    RuntimeError: Jupyter Server Terminals requires Jupyter Server 2.0+
[I 2022-12-27 22:59:05.395 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-12-27 22:59:05.399 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-12-27 22:59:05.399 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-12-27 22:59:05.400 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-12-27 22:59:05.405 ServerApp] nbclassic | extension was successfully linked.
[I 2022-12-27 22:59:05.407 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-12-27 22:59:05.693 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-12-27 22:59:05.717 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-12-27 22:59:05.719 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
[I 2022-12-27 22:59:05.719 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-12-27 22:59:05.723 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-12-27 22:59:05.730 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-12-27 22:59:05.731 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-12-27 22:59:05.732 ServerApp] Jupyter Server 1.23.4 is running at:
[I 2022-12-27 22:59:05.732 ServerApp] http://be2a586ed8ec:8888/lab?token=28c1fd1db847a7c1d9d8e3c663bc3a79e2d3e9be88ec10ee
[I 2022-12-27 22:59:05.733 ServerApp]  or http://127.0.0.1:8888/lab?token=28c1fd1db847a7c1d9d8e3c663bc3a79e2d3e9be88ec10ee
[I 2022-12-27 22:59:05.733 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-12-27 22:59:05.738 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-6-open.html
    Or copy and paste one of these URLs:
        http://be2a586ed8ec:8888/lab?token=28c1fd1db847a7c1d9d8e3c663bc3a79e2d3e9be88ec10ee
     or http://127.0.0.1:8888/lab?token=28c1fd1db847a7c1d9d8e3c663bc3a79e2d3e9be88ec10ee
```

### Expected behavior

I expected jupyter_server version to be 2.0+ just like minimal-notebook is.

### Actual behavior

scipy-notebook complains that Jupyter Server Terminals requires jupyter_server 2.0+ but since it only has 1.23.4, it produces an error.

```
Jupyter Server Terminals requires Jupyter Server 2.0+
```

### Anything else?

Here is the difference in versions comparing minimal-notebook to scipy-notebook:

```
$ IMAGE=jupyter/minimal-notebook; docker pull ${IMAGE} && docker run --rm -it ${IMAGE} jupyter --version
Using default tag: latest
latest: Pulling from jupyter/minimal-notebook
Digest: sha256:d9e7da493ea6c108f61eaf07a19123477643b9aadad1095ea6abd5d615a3c656
Status: Image is up to date for jupyter/minimal-notebook:latest
docker.io/jupyter/minimal-notebook:latest
Selected Jupyter core packages...
IPython          : 8.7.0
ipykernel        : 6.19.4
ipywidgets       : not installed
jupyter_client   : 7.4.8
jupyter_core     : 5.1.0
jupyter_server   : 2.0.5
jupyterlab       : 3.5.2
nbclient         : 0.7.2
nbconvert        : 7.2.7
nbformat         : 5.7.1
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.8.0

$ IMAGE=jupyter/scipy-notebook; docker pull ${IMAGE} && docker run --rm -it ${IMAGE} jupyter --version
Using default tag: latest
latest: Pulling from jupyter/scipy-notebook
Digest: sha256:d04c1e21489cc8c5ee6fe03c5748cf77872ccd6bbaa1cd50cd54ac424b68378a
Status: Image is up to date for jupyter/scipy-notebook:latest
docker.io/jupyter/scipy-notebook:latest
Selected Jupyter core packages...
IPython          : 8.7.0
ipykernel        : 6.19.4
ipywidgets       : 8.0.4
jupyter_client   : 7.3.4
jupyter_core     : 5.1.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.2
nbclient         : 0.7.2
nbconvert        : 7.2.7
nbformat         : 5.7.1
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.8.0
```

Even though scipy-notebook derrives from minimal-notebook, the `mamba install` reinstalls an old version of jupyter_server: https://github.com/jupyter/docker-stacks/blob/6d1862cf30bf4f9ae3f183793438da1f1d7727b7/scipy-notebook/Dockerfile#L29-L61

Although the container does start, inspecting the docker container also shows the container is unhealthy, which prevents my reverse proxy (Traefik) for working with this container:

```
docker inspect jupyterlab-jupyterlab-1 | grep health
                "Status": "unhealthy",
```

**Comment by mathbunnyru** [comment]
I've pinned jupyter_server version and added healthcheck test, so it should work.
I hope I will be able to remove this hotfix in a future.
