### ISSUE TITLE
[BUG] - Error running pre-commit hook: Poetry configuration is invalid

### ISSUE THREAD

**Issue by imiro** [jupyter/docker-stacks#1867]
### What docker image(s) are you using?

base-notebook

### Host OS system and architecture running docker image

MacOS 12/M1 Pro

### What Docker command are you running?

N/A

### How to Reproduce the problem?

I'm following the instructions here: https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/lint.html?highlight=pre-commit#pre-commit-hook-installation

Everything went well up to `make pre-commit-install`

However, the following command:

```
make pre-commit-all
```

Gives the below error

### Command output

```bash session
stderr:
      error: subprocess-exited-with-error

      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/Users/imiro/.cache/pre-commit/repo_hkusprk/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/Users/imiro/.cache/pre-commit/repo_hkusprk/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/Users/imiro/.cache/pre-commit/repo_hkusprk/py_env-python3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/private/var/folders/yx/mj0b3vwj2x7__jrmyjrpqmlm0000gn/T/pip-build-env-b_eci1_h/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/private/var/folders/yx/mj0b3vwj2x7__jrmyjrpqmlm0000gn/T/pip-build-env-b_eci1_h/overlay/lib/python3.9/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.
```

### Actual behavior

An error occured as shown above

### Anything else?

A quick google search on the error message yields two results:

- https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co
- https://github.com/sktime/sktime/issues/4162

Both of which appear to be pretty new (< 24 hours ago)

The suggested solution to update `isort` on the `.pre-commit-config.yaml` to version `5.12.0` does seem to work on my side.

### Latest Docker version

- [X] I've updated my Docker version to the latest available and the issue still persists

**Comment by mathbunnyru** [comment]
I did `rm -rf ~/.cache/pre-commit/` and did `make pre-commit-all` as you.
Got the same error as you.

Then updated isort version and now everything works just fine for me.
I pushed the update to the main branch.

Could you please pull this change, then remove caches and try once again?

**Comment by imiro** [comment]
Yep, can confirm it worked 👍
