### ISSUE TITLE
[BUG] - ServerApp wrote error: 'Forbidden' . Thrown from tornado.web.HTTPError: HTTP 403: Forbidden

### ISSUE THREAD

**Issue by prabhakk-mw** [jupyter/docker-stacks#1919]
### What docker image(s) are you using?

base-notebook

### Host OS system and architecture running docker image

Debian 11

### What Docker command are you running?

`docker run -it --rm --p 8888:8888 jupyter/base-notebook:ubuntu-22.04`

### How to Reproduce the problem?

1. Run container
2. Open a python notebook
3. See terminal output

### Command output

```bash session
docker run -it --rm -p 8888:8888 jupyter/base-notebook:ubuntu-22.04
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[I 2023-06-09 13:45:51.881 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-06-09 13:45:51.907 ServerApp] Package jupyter_lsp took 0.0250s to import
[W 2023-06-09 13:45:51.907 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-09 13:45:51.919 ServerApp] Package jupyter_server_terminals took 0.0116s to import
[I 2023-06-09 13:45:51.921 ServerApp] Package nbclassic took 0.0014s to import
[W 2023-06-09 13:45:51.924 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-09 13:45:51.925 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-06-09 13:45:51.925 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-09 13:45:51.926 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-06-09 13:45:51.933 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-09 13:45:51.938 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-06-09 13:45:51.941 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-06-09 13:45:51.941 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-06-09 13:45:51.943 ServerApp] nbclassic | extension was successfully linked.
[I 2023-06-09 13:45:51.944 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2023-06-09 13:45:52.284 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-06-09 13:45:52.369 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-06-09 13:45:52.371 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-06-09 13:45:52.373 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-09 13:45:52.373 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2023-06-09 13:45:52.374 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2023-06-09 13:45:52.374 LabApp] Extension Manager is 'pypi'.
[I 2023-06-09 13:45:52.377 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-06-09 13:45:52.381 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-06-09 13:45:52.381 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2023-06-09 13:45:52.381 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-09 13:45:52.381 ServerApp] http://9628f9783341:8888/lab?token=0122f2a281af08acc990379eca56ee93f0fe4d7496cfd72c
[I 2023-06-09 13:45:52.381 ServerApp]     http://127.0.0.1:8888/lab?token=0122f2a281af08acc990379eca56ee93f0fe4d7496cfd72c
[I 2023-06-09 13:45:52.381 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-09 13:45:52.384 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-8-open.html
    Or copy and paste one of these URLs:
        http://9628f9783341:8888/lab?token=0122f2a281af08acc990379eca56ee93f0fe4d7496cfd72c
        http://127.0.0.1:8888/lab?token=0122f2a281af08acc990379eca56ee93f0fe4d7496cfd72c
[I 2023-06-09 13:45:53.180 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-06-09 13:46:06.629 LabApp] Build is up to date
[I 2023-06-09 13:46:13.058 ServerApp] Creating new notebook in 
[I 2023-06-09 13:46:13.123 ServerApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[I 2023-06-09 13:46:13.672 ServerApp] Kernel started: 327d4ec4-d08d-45b5-83a4-276ce9a38717
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-06-09 13:46:14.196 ServerApp] Connecting to kernel 327d4ec4-d08d-45b5-83a4-276ce9a38717.
[I 2023-06-09 13:46:14.332 ServerApp] Starting buffering for 327d4ec4-d08d-45b5-83a4-276ce9a38717:6a069834-a4d1-4295-96fa-d17d6217fbe5
[I 2023-06-09 13:46:14.352 ServerApp] Connecting to kernel 327d4ec4-d08d-45b5-83a4-276ce9a38717.
[I 2023-06-09 13:46:14.522 ServerApp] Connecting to kernel 327d4ec4-d08d-45b5-83a4-276ce9a38717.
[W 2023-06-09 13:46:19.978 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2023-06-09 13:46:19.987 ServerApp] 403 GET /api/kernelspecs?1686318379973 (@192.168.0.10) 10.23ms referer=None
```

### Expected behavior

No error messages in terminal

### Actual behavior

throws the following error messages repeatedly:
```
[W 2023-06-09 13:50:32.846 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2023-06-09 13:50:32.848 ServerApp] 403 GET /api/kernelspecs?1686318632840 (@192.168.0.10) 2.70ms referer=None
[I 2023-06-09 13:52:15.427 ServerApp] Saving file at /Untitled.ipynb
[W 2023-06-09 13:52:17.976 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 753, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2023-06-09 13:52:17.978 ServerApp] 403 GET /api/sessions?1686318737971 (@192.168.0.10) 2.71ms referer=None


```

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
@prabhakk-mw could you please clean your browser cache, enable cookies (if you disabled them) and if doesn't work, try another browser?

**Comment by prabhakk-mw** [comment]
That seems to have fixed it. 
Thank you @mathbunnyru !
