### ISSUE TITLE
URL change Docker image

### ISSUE THREAD

**Issue by jhyungjeon** [jupyter/docker-stacks#1997]
### What docker image(s) are you using?

tensorflow-notebook

### Host OS system

k8s container

### Host architecture

x86_64

### What Docker command are you running?

docker run -p 8888:8888 [image]

### How to Reproduce the problem?

Hello. I want to run eclipse-che using the scipy docker image. When I try to run it, I encounter an error: "[Errno 13] Permission denied: '/home/jovyan/.local'". I'm not sure what the cause is.

### Actual behavior

Entered start.sh with args: jupyter lab
There is no entry in /etc/passwd for our UID=1234. Attempting to fix...
Renaming old jovyan user to nayvoj (1000:100)
Added new jovyan user (1234:0). Fixed UID!
WARNING: no write access to /home/jovyan. Try starting the container with group 'users' (100), e.g. using "--group-add=users".
Executing the command: jupyter lab
[I 2023-09-18 04:59:38.922 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-18 04:59:38.928 ServerApp] Package jupyter_lsp took 0.0059s to import
[W 2023-09-18 04:59:38.928 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.930 ServerApp] Package jupyter_server_mathjax took 0.0014s to import
[I 2023-09-18 04:59:38.934 ServerApp] Package jupyter_server_terminals took 0.0036s to import
[I 2023-09-18 04:59:38.951 ServerApp] Package jupyterlab_git took 0.0171s to import
[I 2023-09-18 04:59:38.953 ServerApp] Package nbclassic took 0.0011s to import
[W 2023-09-18 04:59:38.954 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.954 ServerApp] Package nbdime took 0.0000s to import
[I 2023-09-18 04:59:38.954 ServerApp] Package notebook took 0.0000s to import
[I 2023-09-18 04:59:38.955 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-18 04:59:38.955 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-18 04:59:38.956 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-09-18 04:59:38.958 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-09-18 04:59:38.960 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-18 04:59:38.963 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-18 04:59:38.963 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-09-18 04:59:38.965 ServerApp] nbclassic | extension was successfully linked.
[I 2023-09-18 04:59:38.965 ServerApp] nbdime | extension was successfully linked.
[I 2023-09-18 04:59:38.967 ServerApp] notebook | extension was successfully linked.
[W 2023-09-18 04:59:38.968 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 656, in get
        value = obj._trait_values[self.name]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 'browser_open_file'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 656, in get
        value = obj._trait_values[self.name]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 'runtime_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 342, in link_extension
        extension.link_all_points(self.serverapp)
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 224, in link_all_points
        self.link_point(point_name, serverapp)
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 214, in link_point
        point.link(serverapp)
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 136, in link
        linker(serverapp)
      File "/opt/conda/lib/python3.11/site-packages/notebook_shim/nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/notebook_shim/nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
             ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/notebook_shim/nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/inspect.py", line 595, in getmembers
        return _getmembers(object, predicate, getattr)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/inspect.py", line 573, in _getmembers
        value = getter(object, key)
                ^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 703, in __get__
        return self.get(obj, cls)
               ^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 659, in get
        default = obj.trait_defaults(self.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1233, in __call__
        return self.func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 1598, in _default_browser_open_file
        return os.path.join(self.runtime_dir, basename)
                            ^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 703, in __get__
        return self.get(obj, cls)
               ^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 659, in get
        default = obj.trait_defaults(self.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
        return self._get_trait_default_generator(names[0])(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_core/application.py", line 107, in _runtime_dir_default
        ensure_dir_exists(rd, mode=0o700)
      File "/opt/conda/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 25, in ensure_dir_exists
        os.makedirs(path, mode=mode)
      File "<frozen os>", line 215, in makedirs
      File "<frozen os>", line 215, in makedirs
      File "<frozen os>", line 215, in makedirs
      File "<frozen os>", line 225, in makedirs
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 656, in get
    value = obj._trait_values[self.name]
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 607, in launch_instance
    serverapp = cls.initialize_server(argv=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 577, in initialize_server
    serverapp.initialize(
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2548, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 1879, in init_configurables
    connection_dir=self.runtime_dir,
                   ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyter_core/application.py", line 107, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 25, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'


### Anything else?

_No response_

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
`WARNING: no write access to /home/jovyan. Try starting the container with group 'users' (100), e.g. using "--group-add=users".`

Do you mount `/home/jovyan`?
If yes, please, take a look in the [troubleshooting guide](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html).
You need to make sure, that your `/home/jovyan` is write-able.

**Comment by mathbunnyru** [comment]
I am closing this one, as no information has been received from the user, and the troubleshooting guide should help.
