### ISSUE TITLE
Executing the command: jupyter lab fails when using Rosetta for x86/amd64 emulation

### ISSUE THREAD

**Issue by John-Miller12** [jupyter/docker-stacks#1999]
### What docker image(s) are you using?

datascience-notebook, scipy-notebook

### Host OS system

MacOS Ventura 13.5.2 (22G91)

### Host architecture

x86_64

### What Docker command are you running?

`docker run -it -p 8888:8888 --volume /Users/john.miller/Documents/Jupyter:/home/jovyan --platform linux/amd64 --health-interval 15s  jupyter/datascience-notebook:x86_64-latest`
`docker run -it -p 8888:8888 --volume /Users/john.miller/Documents/Jupyter:/home/jovyan --platform linux/amd64 --health-interval 15s  jupyter/datascience-notebook`
`docker run -it -p 8888:8888 --volume /Users/john.miller/Documents/Jupyter:/home/jovyan --platform linux/amd64  jupyter/datascience-notebook`

### How to Reproduce the problem?

On MacBook Pro with M2 Pro Apple Silicon:

- Run docker command
- Await image pull
- Note hang on "Executing the command: jupyter lab"
- Note health checks go 'unhealthy'

### Command output

```bash session
(base) myuser ~ % docker logs 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542

Entered start.sh with args: jupyter lab
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: jupyter lab
^CTraceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 623, in get
    value = obj._trait_values[self.name]  # type: ignore
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/opt/conda/lib/python3.11/site-packages/jupyterlab/labapp.py", line 99, in <module>
    app_version = get_app_version()
                  ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 585, in get_app_version
    handler = _AppHandler(app_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 622, in __init__
    self.registry = options.registry
                    ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __get__
    return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
                     ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 626, in get
    default = obj.trait_defaults(self.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1891, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 1244, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 384, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/jupyterlab/commands.py", line 1996, in _yarn_config
    output_binary = subprocess.check_output(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

### Expected behavior

Jupyter Lab initiates as it does without emulation and no `--platform` flag

### Actual behavior

It just sits on `Executing the command: jupyter lab` indefinitely 

### Anything else?

Thank you for supporting this project!!!

[This StackOverflow](https://stackoverflow.com/questions/75912343/how-to-use-dockers-rosetta-2-x86-64-emulation-when-building-a-docker-image-on-a) roughly summarizes what I was attempting to do. If you have paid Medium access, [this article](https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5) is more succinct.

Events log of first health check failure:
```
(base) john.miller@JohnMillerMBPM1 ~ % docker events
2023-09-27T08:21:10.796859259-05:00 container create 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
2023-09-27T08:21:10.800712467-05:00 container attach 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
2023-09-27T08:21:10.829417217-05:00 network connect 222f6415084442c9d59b86672ee0f5a0f5b734826b4d8a85dd6aa7b9b7819cd1 (container=914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542, name=bridge, type=bridge)
2023-09-27T08:21:10.956144926-05:00 container start 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
2023-09-27T08:21:10.958888384-05:00 container resize 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, height=60, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04, width=180)
2023-09-27T08:21:25.958304377-05:00 container exec_create: /bin/sh -c /etc/jupyter/docker_healthcheck.py || exit 1 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, execID=48a78a9d2b8053bd2919013d72f3a6babe7bf0ef2d3f55f45571d8dc1011b50d, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
2023-09-27T08:21:25.958440044-05:00 container exec_start: /bin/sh -c /etc/jupyter/docker_healthcheck.py || exit 1 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, execID=48a78a9d2b8053bd2919013d72f3a6babe7bf0ef2d3f55f45571d8dc1011b50d, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
2023-09-27T08:21:26.220016710-05:00 container exec_die 914b1b5d846829145e85fcdca2518c48cf19ec56605f346ba3541a3c1fae9542 (desktop.docker.io/binds/0/Source=/Users/john.miller/Documents/Jupyter, desktop.docker.io/binds/0/SourceKind=hostFile, desktop.docker.io/binds/0/Target=/home/jovyan, execID=48a78a9d2b8053bd2919013d72f3a6babe7bf0ef2d3f55f45571d8dc1011b50d, exitCode=1, image=jupyter/datascience-notebook:x86_64-latest, maintainer=Jupyter Project <jupyter@googlegroups.com>, name=vigilant_almeida, org.opencontainers.image.ref.name=ubuntu, org.opencontainers.image.version=22.04)
```

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by consideRatio** [comment]
Isn't the M line of apple computers arm64 based?

Does this reproduce if you dont mount your home folder also?

**Comment by John-Miller12** [comment]
@consideRatio you're correct, they are arm64 based. I need to use a python package that is not yet supported on arm64, hence the attempts to run in emulation with `--platform linux/amd64`. The `datascience-notebook:latest` image runs fine and Jupyter Lab initiates without the `--platform` flag, but I cannot install the required packages in that container. 

It does reproduce. I just attempted `docker run -it -p 8888:8888 --platform linux/amd64 --health-interval 15s  jupyter/datascience-notebook` to the same effect.

**Comment by mathbunnyru** [comment]
I have M2 Macbook Air, macOS Sonoma 14.0 (23A344).

`docker run -it -p 8888:8888 --platform linux/amd64 --health-interval 15s  jupyter/datascience-notebook` works fine for me.
It takes around 4 seconds after the line `Executing the command: jupyter lab` to actually start doing something.

My Docker Desktop Version is: `4.23.0 (120376)`, Engine: `24.0.6`
Could you please check your version?

I also tried enabling/disabling Rosetta setting in Docker Desktop - still seems to work in both cases.

**Comment by John-Miller12** [comment]
@mathbunnyru That is both encouraging and frustrating to know it works for you!

My Docker Desktop and Engine versions are the same as those listed. I am executing from the native zsh terminal.

**Comment by John-Miller12** [comment]
Inspired by @mathbunnyru, I've tried toggling Rosetta off:

**1. Success**: 
without Rosetta: `docker run -it -p 8888:8888  --platform linux/amd64  jupyter/datascience-notebook` - the x86_64 packages installed
**2. Success**: 
without Rosetta: same as above with --volume 
**3. Failure**:
toggling Rosetta, then `docker start -i <container_from_2>` - hangs on `Executing the command: jupyter lab`
**4. Failure**:
with Rosetta, the same `docker run` as used in 2. hangs on jupyter lab.
**5. Failure**:
with Rosetta, 'docker start -i <container_from_1>`. hangs on jupyter lab.
**6. Failure**:
with Rosetta, the same 'docker run' as used in 1. hangs on jupyter lab.

As soon as i toggle Rosetta off, all 4 containers start with `docker start -i <id>`

I'm new to x86_64 emulation. From what I can tell from a web search, QEMU is just as functional as Rosetta, but [much slower.](https://patrickwthomas.net/macos-docker/#:~:text=The%20QEMU%20container%20performed%20worse,ran%20across%20all%208%20cores.)

I still need to update to Sonoma, and will update this ticket tomorrow once done.

**Comment by John-Miller12** [comment]
`docker run -it -p 8888:8888 --volume /Users/john.miller/Documents/Jupyter:/home/jovyan --platform linux/amd64  jupyter/datascience-notebook` is successful after updating to Sonoma 14.0

**Comment by mathbunnyru** [comment]
Great! I'm glad I was able to help 😄
