### ISSUE TITLE
seems broken: Infinite API requests to api/kernels/<changing-constantly>/channels?session_id=<changing-constantly> and kernel error

### ISSUE THREAD

**Issue by imagineLife** [jupyter/docker-stacks#2092]
### What docker image(s) are you using?

tensorflow-notebook

### Host OS system

MacOS 14.1.2 (23B92)

### Host architecture

x86_64

### What Docker command are you running?

docker run -it --name jp -p 8080:8888 -v /Users/<my-user>/Documents/jupyter-files:/home/jovyan/work -e NB_UID=1000 quay.io/jupyter/tensorflow-notebook

### How to Reproduce the problem?

- run that docker command, including a set of jupyter notebook files. I'm using a pretty simple notebook file with a few "trivial" python cells - here's the first cell contents:
```python
listOfNumbers = [1, 2, 3, 4, 5, 6]

for number in listOfNumbers:
    print(number)
    if (number % 2 == 0):
        print("is even")
    else:
        print("is odd")
```
- open the jupyter notebook GUI in a browser using localhost:8080/?token=<get-the-token>
- select the notebook file & attempt to "run" the cell
- notice the "bugs": the cell doesn't seem to "run" nor output/print anything, there are infinte api requests (more on this below) and a Modal will appear reading `Error starting kernel: Missing property "id"`

### Command output

```bash session
Jakes-4:big-site Jake$ docker run -it --name jp -p 8080:8888 -v /Users/<me>/Documents/notebooks:/home/jovyan/work -e NB_UID=1000 quay.io/jupyter/tensorflow-notebook
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: start-notebook.py
Executing: jupyter lab
[I 2024-02-07 15:12:02.186 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-07 15:12:02.189 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-02-07 15:12:02.192 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-07 15:12:02.196 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-07 15:12:02.196 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-02-07 15:12:02.198 ServerApp] nbclassic | extension was successfully linked.
[I 2024-02-07 15:12:02.198 ServerApp] nbdime | extension was successfully linked.
[I 2024-02-07 15:12:02.201 ServerApp] notebook | extension was successfully linked.
[I 2024-02-07 15:12:02.203 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-02-07 15:12:02.416 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-07 15:12:02.430 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-07 15:12:02.432 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-07 15:12:02.432 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-02-07 15:12:02.433 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-07 15:12:02.436 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-02-07 15:12:02.436 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-02-07 15:12:02.436 LabApp] Extension Manager is 'pypi'.
[I 2024-02-07 15:12:02.446 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-07 15:12:02.449 ServerApp] jupyterlab_git | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-02-07 15:12:02.452 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-02-07 15:12:02.498 ServerApp] nbdime | extension was successfully loaded.
[I 2024-02-07 15:12:02.501 ServerApp] notebook | extension was successfully loaded.
[I 2024-02-07 15:12:02.502 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2024-02-07 15:12:02.502 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-02-07 15:12:02.502 ServerApp] http://1ae61382e2fe:8888/lab?token=2544729375d067cdf993225142a51d7c7a34bdd782524599
[I 2024-02-07 15:12:02.503 ServerApp]     http://127.0.0.1:8888/lab?token=2544729375d067cdf993225142a51d7c7a34bdd782524599
[I 2024-02-07 15:12:02.503 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-07 15:12:02.505 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
    Or copy and paste one of these URLs:
        http://1ae61382e2fe:8888/lab?token=2544729375d067cdf993225142a51d7c7a34bdd782524599
        http://127.0.0.1:8888/lab?token=2544729375d067cdf993225142a51d7c7a34bdd782524599
[I 2024-02-07 15:12:03.667 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-07 15:12:36.886 LabApp] Build is up to date
[I 2024-02-07 15:13:02.896 ServerApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[W 2024-02-07 15:13:02.897 ServerApp] Notebook work/Python101.ipynb is not trusted
[I 2024-02-07 15:13:03.672 ServerApp] Kernel started: 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-07 15:13:04.421 ServerApp] Connecting to kernel 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9.
[I 2024-02-07 15:13:04.430 ServerApp] Starting buffering for 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9:f3f748fb-c93a-49a2-abe9-7cf8e23a24c2
[I 2024-02-07 15:13:04.436 ServerApp] Connecting to kernel 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9.
[I 2024-02-07 15:13:04.436 ServerApp] Discarding 3 buffered messages for 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9:f3f748fb-c93a-49a2-abe9-7cf8e23a24c2
[I 2024-02-07 15:13:04.443 ServerApp] Starting buffering for 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9:e9363994-1cd1-4e8c-9d11-cb75a85aed0e
[I 2024-02-07 15:13:04.452 ServerApp] Connecting to kernel 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9.
[I 2024-02-07 15:13:04.453 ServerApp] Discarding 3 buffered messages for 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9:e9363994-1cd1-4e8c-9d11-cb75a85aed0e
[I 2024-02-07 15:13:04.461 ServerApp] Starting buffering for 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9:f3f748fb-c93a-49a2-abe9-7cf8e23a24c2
[I 2024-02-07 15:13:04.467 ServerApp] Connecting to kernel 5ed9f88a-7f42-4a74-ba70-d60de93aa3b9.
...etc...
```

### Expected behavior

A "functioning" jupyter notebook gui, hosted by a docker container on my M1 macbook

### Actual behavior

1. The closest thing I can find to a container cli error output is by doing the above bug-reproduction steps, closing the browser window, and re-starting the reproduction steps. the container logs show...
```bash
[E 2024-02-07 15:14:21.110 ServerApp] Uncaught exception GET /api/kernels/969f91ad-07da-4852-a9c4-4dd8f1d968c3/channels?session_id=30c0df59-259f-4d03-9aa2-b91952a2e445 (192.168.65.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8080', method='GET', uri='/api/kernels/969f91ad-07da-4852-a9c4-4dd8f1d968c3/channels?session_id=30c0df59-259f-4d03-9aa2-b91952a2e445', version='HTTP/1.1', remote_ip='192.168.65.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/services/kernels/websocket.py", line 67, in get
        await self.pre_get()
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/services/kernels/websocket.py", line 62, in pre_get
        await self.connection.prepare()
      File "/opt/conda/lib/python3.11/site-packages/jupyter_server/services/kernels/connection/channels.py", line 317, in prepare
        raise TimeoutError(msg)
    TimeoutError: Kernel never reached an 'alive' state.
[E 2024-02-07 15:14:21.148 ServerApp] {
      "Host": "127.0.0.1:8080",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
    }
[E 2024-02-07 15:14:21.148 ServerApp] 500 GET /api/kernels/969f91ad-07da-4852-a9c4-4dd8f1d968c3/channels?session_id=30c0df59-259f-4d03-9aa2-b91952a2e445 (426a3dba1d89491f8e845c8c7d0cc28d@192.168.65.1) 60305.64ms referer=None
[I 2024-02-07 15:14:33.921 ServerApp] Kernel started: cd1d46c1-b611-483d-aa17-575751214220
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-07 15:14:34.584 ServerApp] Connecting to kernel cd1d46c1-b611-483d-aa17-575751214220.
[I 2024-02-07 15:14:34.593 ServerApp] Starting buffering for cd1d46c1-b611-483d-aa17-575751214220:48625c6e-311a-497e-b229-d28ca056b24f
[I 2024-02-07 15:14:34.599 ServerApp] Connecting to kernel cd1d46c1-b611-483d-aa17-575751214220.
[I 2024-02-07 15:14:34.599 ServerApp] Discarding 3 buffered messages for cd1d46c1-b611-483d-aa17-575751214220:48625c6e-311a-497e-b229-d28ca056b24f
[I 2024-02-07 15:14:34.606 ServerApp] Starting buffering for cd1d46c1-b611-483d-aa17-575751214220:c43f75c6-9d34-4891-ba99-cf5882471322
[I 2024-02-07 15:14:34.615 ServerApp] Connecting to kernel cd1d46c1-b611-483d-aa17-575751214220.
```

3. as noted in the issue title, infinite api requests can be seen in the browser devTools network requests to api/kernels/<changing-constantly>/channels?session_id=<changing-constantly>

4. 

### Anything else?

Thanks ahead of time to any help offered here!!  
I haven't seemed to find iterations of these "exact" issues I'm having - perhaps/hopefully i'm just missing something trivial

![Screenshot 2024-02-07 at 10 14 37 AM](https://github.com/jupyter/docker-stacks/assets/24195040/0fc3c184-bf62-4995-bfcc-7c1fe7a8eb45)
![Screenshot 2024-02-07 at 10 14 03 AM](https://github.com/jupyter/docker-stacks/assets/24195040/ff530b92-9253-4130-8694-99acefe5a09b)  
Once I select "OK" on the `Error` dialogue, I am prompted to select a kernel, & the only option seems to be this `Python 3(ipykernel)`option, so i select it to no seeming changes - 
![Screenshot 2024-02-07 at 10 36 10 AM](https://github.com/jupyter/docker-stacks/assets/24195040/26f9a40c-7563-4d4a-8f76-7c230454b4cb)  

Also, I've disconnected from the kernel as well as from "all" kernels using the kernel dropdown in the jupyter notebook gui toolbar - those don't seem to "help" either :/  

Also, I did download the latest version of docker once i noticed the checkbox below, and now I'm using
```bash
Docker version 25.0.2, build 29cf629
```
No changes after docker update :/ 

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
Could you please try running our image without volume mount?
And then create a file and run it as you did in your example.

Chances are the volume mount creates issues, not the image itself.

**Comment by imagineLife** [comment]
hi @mathbunnyru thanks for the suggestion to try without the volume mount, **TL;DR seems like the same experience :/**   
The bottom of this copy-paste cli output is the beginning of the infinitely repeating api requests from the browser:

```bash
Jakes-4:big-site Jake$ docker run -it --name jp -p 8080:8888 quay.io/jupyter/tensorflow-notebook
Entered start.sh with args: start-notebook.py
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: start-notebook.py
Executing: jupyter lab
[I 2024-02-08 14:42:25.997 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-08 14:42:26.001 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-02-08 14:42:26.004 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-08 14:42:26.008 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-08 14:42:26.008 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-02-08 14:42:26.010 ServerApp] nbclassic | extension was successfully linked.
[I 2024-02-08 14:42:26.011 ServerApp] nbdime | extension was successfully linked.
[I 2024-02-08 14:42:26.014 ServerApp] notebook | extension was successfully linked.
[I 2024-02-08 14:42:26.015 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-02-08 14:42:26.219 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-08 14:42:26.232 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-08 14:42:26.234 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-08 14:42:26.234 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-02-08 14:42:26.235 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-08 14:42:26.236 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2024-02-08 14:42:26.236 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2024-02-08 14:42:26.237 LabApp] Extension Manager is 'pypi'.
[I 2024-02-08 14:42:26.246 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-08 14:42:26.249 ServerApp] jupyterlab_git | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2024-02-08 14:42:26.252 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-02-08 14:42:26.290 ServerApp] nbdime | extension was successfully loaded.
[I 2024-02-08 14:42:26.292 ServerApp] notebook | extension was successfully loaded.
[I 2024-02-08 14:42:26.293 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2024-02-08 14:42:26.293 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-02-08 14:42:26.293 ServerApp] http://278316584f80:8888/lab?token=826fdf77a1a869d159b704fe190eed72efb24c35bea55265
[I 2024-02-08 14:42:26.293 ServerApp]     http://127.0.0.1:8888/lab?token=826fdf77a1a869d159b704fe190eed72efb24c35bea55265
[I 2024-02-08 14:42:26.293 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-08 14:42:26.295 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-7-open.html
    Or copy and paste one of these URLs:
        http://278316584f80:8888/lab?token=826fdf77a1a869d159b704fe190eed72efb24c35bea55265
        http://127.0.0.1:8888/lab?token=826fdf77a1a869d159b704fe190eed72efb24c35bea55265
[I 2024-02-08 14:42:26.653 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-02-08 14:42:36.196 ServerApp] 302 GET /?token=[secret] (@192.168.65.1) 1.09ms
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-08 14:42:39.545 LabApp] Build is up to date
[I 2024-02-08 14:42:43.251 ServerApp] Creating new notebook in /work
[I 2024-02-08 14:42:43.342 ServerApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[I 2024-02-08 14:42:44.032 ServerApp] Kernel started: 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-08 14:42:44.883 ServerApp] Connecting to kernel 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7.
[I 2024-02-08 14:42:44.885 ServerApp] Connecting to kernel 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7.
[W 2024-02-08 14:42:44.896 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0xffff8f7a8dd0>
[I 2024-02-08 14:42:44.906 ServerApp] Starting buffering for 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7:155b8e60-6d6f-4495-a120-be6d08d9feb2
[I 2024-02-08 14:42:44.907 ServerApp] Connecting to kernel 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7.
[I 2024-02-08 14:42:44.908 ServerApp] Discarding 2 buffered messages for 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7:155b8e60-6d6f-4495-a120-be6d08d9feb2
[W 2024-02-08 14:42:44.909 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0xffff8f75aad0>
[W 2024-02-08 14:42:44.909 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0xffff8f75aad0>
[I 2024-02-08 14:42:44.917 ServerApp] Starting buffering for 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7:cb98ff81-09dd-463a-8c7b-64cdb0b493a8
[I 2024-02-08 14:42:44.922 ServerApp] Connecting to kernel 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7.
[I 2024-02-08 14:42:44.923 ServerApp] Discarding 3 buffered messages for 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7:cb98ff81-09dd-463a-8c7b-64cdb0b493a8
[I 2024-02-08 14:42:44.940 ServerApp] Starting buffering for 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7:155b8e60-6d6f-4495-a120-be6d08d9feb2
[I 2024-02-08 14:42:44.943 ServerApp] Connecting to kernel 6d57bc9c-2bdb-4063-9f39-b5dacd8610d7.
```

I get the same 2 error dialogues, `Error Starting Kernel` with subtext `Missing property 'id'`, followed by the `Select Kernel` dialogue

**Comment by imagineLife** [comment]
**Working Discovery**  
Exposing the same port, `8888`, to the host removes the errors.  
I can even mount a volume.  👍 

```docker run -it --name jp -p 8888:8888 -v /Users/<me>/Documents/<my-docs>:/home/jovyan/work quay.io/jupyter/tensorflow-notebook```


**Is this an expected requirement/restriction**, to be required to expose the exact same port that runs "internally" in the container to the host machine like that? [The docs seem to explain that the port can be changed between the container and the host](https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html#example-1)

**Comment by mathbunnyru** [comment]
There is no such limit. Docker container doesn’t know which port it forwards to.
Is there a chance you have a browser tab, which tries to reload the page?
It can also be vs code.
