### ISSUE TITLE
Regression: changing NB_UID

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#269]
The start.sh script changes the owner of `.` which is the `/home/jovyan/work directory` but misses changing `/home/jovyan/` so notebook (and the user) have no access to write files anywhere in the home dir.

I think we purposely took out the chown at one point to avoid changing ownership over files when the home directory is host mounted. But clearly that breaks when the home dir is NOT mounted as seen below.

```
pparente@VM4-002 ~ ❯❯❯ docker run -it --rm -p 8888:8888 -e NB_UID=$(id -u) --user root -v /home/pparente/test:/home/jovyan/work jupyter/scipy-notebook
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 842, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime'
```

**Comment by parente** [comment]
Ideas:

- Inspect files/directories more carefully when changing ownership to determine which should be touched and which should not.
- Create a new user account in the container with a new home directory, populate that home directory in the same manner as the default `jovyan` dir, and chown `/opt/conda` only.

**Comment by amatsus** [comment]
It's a bug of aufs and overlayfs. The patch has been applied to them and it will be available soon in your environment.

[AUFS broken permissions? #20240](https://github.com/docker/docker/issues/20240)
[permissions broken after chown #24913](https://github.com/docker/docker/issues/24913)

**Comment by parente** [comment]
@amatsus thanks for that bit of info. I still think we have a problem in https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L12 too. We're only chown'ing the conda directory. We're not doing anything to fix the ownership on `~jovyan`.

**Comment by parente** [comment]
Ah, never mind my last comment. I remember now. chown takes care of the homedir uid changes automatically.

```
man chown

...

-u, --uid UID

...

The user's mailbox, and any files which the user owns and which are located in the 
user's home directory will have the file user ID changed automatically.

The ownership of files outside of the user's home directory must be fixed manually.
```

**Comment by amatsus** [comment]
Code related to this union filesystem issue is located at [master/base-notebook/Dockerfile#L53](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L53) and [master/base-notebook/start.sh#L11](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L11).

I propose amatsus@1638a0f to avoid this issue. It works now with all docker graph driver. FYI, I don't need it, so I have applied a patch to the linux kernel myself.

**Comment by amatsus** [comment]
Docker just released Docker for Mac/Windows 1.12.1-beta26 now and it fix this issue.

https://docs.docker.com/docker-for-mac/release-notes/#/beta-release-notes
https://docs.docker.com/docker-for-windows/release-notes/#/beta-release-notes

**Comment by parente** [comment]
The new version does fix the original issue. However, I now get a disk I/O error trying to create or open a host mounted notebook.

**Comment by parente** [comment]
Creating a new notebook leads to the following exception. 

```
[E 02:00:50.619 NotebookApp] Error while saving file: Untitled.ipynb disk I/O error
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'db'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/opt/conda/lib/python3.5/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/sign.py", line 246, in sign
        self.store_signature(signature, nb)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/sign.py", line 249, in store_signature
        if self.db is None:
      File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/opt/conda/lib/python3.5/site-packages/nbformat/sign.py", line 127, in _db_default
        self.init_db(db)
      File "/opt/conda/lib/python3.5/site-packages/nbformat/sign.py", line 139, in init_db
        )""")
    sqlite3.OperationalError: disk I/O error
```
