### ISSUE TITLE
Permission denied on container directory when mounting SSL cert + key

### ISSUE THREAD

**Issue by clintworrell** [jupyter/docker-stacks#303]
When running the following:
docker run -d -e USE_HTTPS=yes -v /home/testing/test.pem:/home/jovyan/.local/share/jupyter/notebook.pem -p 8080-9999:8888 jupyter/datascience-notebook

The container doesn't start and the logs show the following:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 842, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime'

I'm able to mount the working directory fine. I'm new to Docker so apologies if I'm missing something simple. I've spent hours trying to figure out a solution to no avail. Thanks for any help.

Ubuntu 14.04.5
Docker 1.12.3
jupyter/datascience-notebook:latest

**Comment by parente** [comment]
You're not doing anything wrong. This is a bug in the instructions and setup for host mounting the PEM file. When mounting it, docker winds up making all of the parent directories writable only by root.

We really need to change where the startup script looks for / generates the PEM file.

**Comment by clintworrell** [comment]
Thanks for the quick response. Is there a workaround other than using a self-signed cert? Also, first time using GitHub Issues, is it protocol for me to close the issue now that I have an answer?

**Comment by parente** [comment]
> Is there a workaround other than using a self-signed cert?

If you don't specify a cert volume mounted from the host and instead let the notebook startup script generate one, you'll side step the problem. The README describes the flags to see for this approach. (I forget the exact env vars.)

> Also, first time using GitHub Issues, is it protocol for me to close the issue now that I have an answer?

Congrats on your first post! 🍰  I've marked this issue a bug because what you're trying to do should really work. Let's leave the issue open so that I (or someone else who wants to contribute) can fix it properly.

**Comment by parente** [comment]
The configuration changes in PR #322 resolve this. Check out the READMEs for the new instructions.
