### ISSUE TITLE
Unable to install scipy/notebook "unexpected EOF"

### ISSUE THREAD

**Issue by MattDelac** [jupyter/docker-stacks#306]
Hello,

Last week, I could make it work but today it does not work. It seems like an image is broken ...

If I run a simple "docker pull jupyter/scipy-notebook" it stops while dowloading:
7be21907f026: Downloading [===>                                               ] 50.82 MB/660.7 MB
832565bb6043: Downloading [========>                                          ] 38.93 MB/223.1 MB
unexpected EOF

I always have issues with one of these images.

Do you have any idea ?

Thank you
Matt

**Comment by MattDelac** [comment]
And if I try with docker-compose:

7be21907f026: Downloading [=>                                                 ] 14.06 MB/660.7 MB
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 382, in up
  File "compose/service.py", line 305, in ensure_image_exists
  File "compose/service.py", line 731, in build
  File "compose/progress_stream.py", line 18, in stream_output
  File "compose/utils.py", line 57, in split_buffer
  File "compose/utils.py", line 33, in stream_as_text
  File "site-packages/docker/client.py", line 245, in _stream_helper
  File "site-packages/requests/packages/urllib3/response.py", line 271, in read
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
docker-compose returned -1

**Comment by parente** [comment]
@MattDelac Those EOFs are coming from the docker CLI trying to download the (massive) images from Docker Hub. They typically happen when you've got an unreliable connection to the Docker Hub site or the site itself is having issues.

I just pulled the images here and everything went smoothly, which I know doesn't help much other than to indicate that there's nothing wrong with the images themselves.

**Comment by MattDelac** [comment]
@parente OK, I will check docker cli.

Thank you for your fast response !

**Comment by parente** [comment]
I'm going to close this issue. @MattDelac feel free to reopen if you do find it's a problem with the images that I missed.
