### ISSUE TITLE
KeyError: 'runtime_dir' trying to run the container with jupyter/all-spark-notebook

### ISSUE THREAD

**Issue by printztxikia** [jupyter/docker-stacks#526]
Thanks in advance!

**What docker image you are using?**
jupyter/all-spark-notebook
**What complete docker command do you run to launch the container (omitting sensitive values)?**
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook

**What steps do you take once the container is running to reproduce the issue?**

Nothing, just running the container as listed above is causing the error.

**What actually happens?**
Executing the command: jupyter notebook
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1366, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1100, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/home/jovyan/.local/share/jupyter/runtime'

**Comment by parente** [comment]
I pulled the latest `jupyter/all-spark-notebook` image and ran `docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook` locally. The notebook server started up without incident. 

The `No space left on device` error suggests the hard drive where your docker images are stored is out of space. If you're running docker for mac or windows, it could be the VM is out of space rather than your host machine. Can you double check?

**Comment by printztxikia** [comment]
:S you were right @parente , I had 18GB size of VM, and as soon as I've clean it, worked perfectly. Apologies for wasting your time...

**Comment by parente** [comment]
No problem. Happy Jupyter-ing!
