### ISSUE TITLE
Unable to run jupyter/minimal-notebook: ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by jonatasbaldin** [jupyter/docker-stacks#564]
**What docker image you are using?**
`jupyter/minimal-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
`$ docker run -it --rm -p 8888:8888 jupyter/minimal-notebook`

**What steps do you take once the container is running to reproduce the issue?**
Just run the command.

**What do you expect to happen?**
A URL to access the notebook.

**What actually happens?**
```
➜  ~ docker run  --rm -p 8888:8888 jupyter/minimal-notebook
Container must be run with group root to update passwd file
Executing the command: jupyter notebook
[I 22:44:11.252 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1368, in initialize
    self.init_webapp()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1161, in init_webapp
    self.jinja_environment_options
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 154, in __init__
    base_url, default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 263, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 874, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/opt/conda/lib/python3.6/site-packages/IPython/__init__.py", line 54, in <module>
    from .core.application import Application
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/opt/conda/lib/python3.6/site-packages/IPython/core/ultratb.py", line 120, in <module>
    from IPython.utils import path as util_path
  File "/opt/conda/lib/python3.6/site-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/opt/conda/lib/python3.6/site-packages/IPython/utils/process.py", line 18, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/opt/conda/lib/python3.6/site-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
ValueError: source code string cannot contain null bytes
```

**Version of things**
```
➜  ~ docker -v
Docker version 17.12.0-ce, build c97c6d6

➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
``` 

Thanks!

**Comment by parente** [comment]
Hmm. The `Container must be run with group root to update passwd file` bit made me think it was a regression related to PR #559. I just pulled the latest `jupyter/minimal-notebook` image locally on Linux and ran without an issue. Pulling it on my Mac at the moment to try there ...

**Comment by parente** [comment]
No issues on my mac either. Do you have the latest minimal-notebook image? Should have ID 83cc55e10b0f from about 5 days ago.

```
Last login: Sun Feb 25 17:08:52 on ttys004
~ ❯❯❯ docker -v
Docker version 17.12.0-ce, build c97c6d6
~ ❯❯❯ docker run -it --rm -p 8888:8888 jupyter/minimal-notebook
Container must be run with group root to update passwd file
Executing the command: jupyter notebook
[I 03:22:03.451 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 03:22:03.815 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 03:22:03.857 NotebookApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 03:22:03.857 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 03:22:03.867 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 03:22:03.867 NotebookApp] 0 active kernels
[I 03:22:03.867 NotebookApp] The Jupyter Notebook is running at:
[I 03:22:03.868 NotebookApp] http://[all ip addresses on your system]:8888/?token=b306964eb98c413ece22d460b06e46ea1d6999f7aa14037a
[I 03:22:03.868 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 03:22:03.869 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b306964eb98c413ece22d460b06e46ea1d6999f7aa14037a
```

**Comment by jonatasbaldin** [comment]
Hello there, thanks for the responses.

Yes, I have this version. Still having the same issue 🤔 Will try to remove the image and pull it again!

**Comment by jonatasbaldin** [comment]
Hello! Just pulled the image again and it working fine, it maybe got corrupted while pulling it before.

Thanks for the attention ❤️
