### ISSUE TITLE
Crashing bug introduced in latest image of all-spark-notebook

### ISSUE THREAD

**Issue by AronT-TLV** [jupyter/docker-stacks#710]
**What docker image you are using?**

`jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Ran it in Azure ACI:

`az container create -g xxxxx --name xxxxx -e JUPYTER_ENABLE_LAB=yes --image jupyter/all-spark-notebook:latest --ports 8888 --ip-address public --cpu 2 --memory 8  --azure-file-volume-account-name xxxxxxxx  --azure-file-volume-account-key $STORAGE_KEY  --azure-file-volume-share-name xxxxxx --azure-file-volume-mount-path /home/jovyan/work`

**What steps do you take once the container is running to reproduce the issue?**

1. Went to the Jupiter lab in my browser
2. Start a Scala Toree notebook
3. Put `5 + 5` in the cell and ran the cell

**What do you expect to happen?**

I would get output of 10

**What actually happens?**

No output is visible in the notebook and the notebook server log contains following message:

```
2018-08-27 19:42:57 ERROR OneForOneStrategy:159 - JsResultException(errors:List((/deletedCells,List(ValidationError(error.expected.jsstring,WrappedArray())))))
play.api.libs.json.JsResultException: JsResultException(errors:List((/deletedCells,List(ValidationError(error.expected.jsstring,WrappedArray())))))
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:77)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsValue$class.as(JsValue.scala:65)
	at play.api.libs.json.JsObject.as(JsValue.scala:166)
	at org.apache.toree.kernel.protocol.v5.kernel.Utilities$.ZMQMessageToKernelMessage(Utilities.scala:69)
	at org.apache.toree.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket$$anonfun$receive$1.applyOrElse(ZeromqKernelMessageSocket.scala:48)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at org.apache.toree.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket.aroundReceive(ZeromqKernelMessageSocket.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-08-27 19:42:57 ERROR ZeroMQSocketRunnable:167 - Unexpected exception in 0mq socket runnable!
org.zeromq.ZMQException: Errno 48 : Address already in use
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1425)
	at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1187)
	at org.zeromq.ZMQ$Socket.bind(ZMQ.java:1148)
	at org.apache.toree.communication.socket.ZeroMQSocketRunnable$$anonfun$processOptions$2.apply(ZeroMQSocketRunnable.scala:88)
	at org.apache.toree.communication.socket.ZeroMQSocketRunnable$$anonfun$processOptions$2.apply(ZeroMQSocketRunnable.scala:87)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at org.apache.toree.communication.socket.ZeroMQSocketRunnable.processOptions(ZeroMQSocketRunnable.scala:87)
	at org.apache.toree.communication.socket.ZeroMQSocketRunnable.run(ZeroMQSocketRunnable.scala:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Note the following additional points:**
1. When I open a terminal and run `spark-shell` it works fine
2. When I run an ACI image with previous version of the docker image, `177037d09156` it works fine
3. The problem seems to have been introduced in image `8ccdfc1da8d5` based on the latest code commit
4. I gave the example of `5+5` because its the simplest way to replicate the problem, but the fact is all commands run in cells display no output and give same error

**Comment by parente** [comment]
I'm seeing the same thing when launching `jupyter/all-spark-notebook:8ccdfc1da8d5` on binder via this gist https://gist.github.com/parente/714c91cd28314fa31c4bd67ebc0453b8, but only using JupyterLab. The Toree behaves correctly with the classic Jupyter Notebook in that same image. That's very odd behavior considering both UIs are using the same underlying notebook server and Toree kernel stack.

There is a Toree 0.2.0-incubating final release available. The images are still using 0.2.0-RC5: https://github.com/jupyter/docker-stacks/blob/master/all-spark-notebook/Dockerfile#L37. Perhaps the latest stable release corrects a compatibility problem? I'd be happy to review a PR updating Toree regardless.

**Comment by vishnu2kmohan** [comment]
Yes, the problem only manifests while attempting to launch Apache Toree kernels **only** from JupyterLab and **not** from the _Classic_ Jupyter Notebook.

(I forgot to add that nuance earlier, thanks @parente for the additional clarification).

The issue occurs with the `-rc5` and `-rc6` versions (Note: `rc-6` has been [promoted](https://dist.apache.org/repos/dist/release/incubator/toree/0.2.0-incubating/toree-pip/toree-0.2.0.tar.gz) to the [official 0.2.0 GA release](https://github.com/dcos-labs/dcos-jupyterlab-service/blob/master/jupyter-root-conda-base-env.yml#L103)) only under JupyterLab 0.34.x and does not manifest when running under JupyterLab 0.33.x :man_shrugging:

Hoping someone with experience in both JupyterLab and Apache Toree can figure out what caused things to break between 0.33.x and 0.34.x :crossed_fingers:

**Comment by justdoit0823** [comment]
This issue was reported at toree-dev [jira](http://mail-archives.apache.org/mod_mbox/toree-dev/201809.mbox/%3cJIRA.13187591.1537965446000.170246.1537977540077@Atlassian.JIRA%3e), which explained how this issue happened, and here [this](http://mail-archives.apache.org/mod_mbox/toree-dev/201809.mbox/%3cJIRA.13187591.1537965446000.6832.1538341980301@Atlassian.JIRA%3e) gives some advice to solve this problem.

**Comment by lresende** [comment]
Sorry, I didn't see this before on this side of the house. 
We need a new release of Toree, let me see if I can work on that asap. Another option is to downgrade lab to before 0.32.4. Full details of the issue can be found at [TOREE-485](https://issues.apache.org/jira/browse/TOREE-485)

**Comment by lresende** [comment]
PR #726 should fix this issue.

**Comment by vishnu2kmohan** [comment]
> PR #726 should fix this issue.
Yep, [confirmed](https://github.com/dcos-labs/dcos-jupyterlab-service/commit/beb3635515b49221bc992203433f58ec4d882854). Thanks @lresende!
