### ISSUE TITLE
conda install pyodbc fails with Python TypeError

### ISSUE THREAD

**Issue by pgeez** [jupyter/docker-stacks#730]
**What docker image you are using?**

`jupyter/base-notebook:6d2a05346196`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

doing this from inside a container, so simply...

`docker run -it jupyter/base-notebook:6d2a05346196 /bin/bash`

**What steps do you take once the container is running to reproduce the issue?**

From inside the running container...

1. update Conda (to 4.5.11): `conda update -n base conda`
2. attempt to install PyODBC: `conda install -c anaconda pyodbc`

**What do you expect to happen?**

PyODBC installs

**What actually happens?**

Error.

```
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 218, in _load
        mod_etag_headers.get('_mod'))
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /opt/conda/bin/conda install -c anaconda pyodbc`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_DIR=/opt/conda
               CONDA_ROOT=/opt/conda
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.5 Linux/4.10.0-35-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

**Comment by ericdill** [comment]
Out of curiosity, why do you need to install from the `anaconda` channel? This works just fine if you run `conda install pyodbc` (i.e., without the `-c anaconda`)

**Comment by pgeez** [comment]
Thanks @ericdill ! I'll give that a try.

As for why, the docs:

https://anaconda.org/anaconda/pyodbc

**Comment by ericdill** [comment]
@pgeez got it. Thanks for the explanation. I've forwarded this usability issue to the conda distribution team. For what it's worth, I'd stay away from the `anaconda` channel instead preferring the `defaults` channel. I believe that the description of the anaconda channel has been recently updated (possibly as a result of your UX issue) to suggest this approach:

> This channel is used internally for mirroring. You should very much prefer https://repo.anaconda.com, which is conda's default and needs no "-c" setting.

**Comment by parente** [comment]
This issue has been inactive for some time now and so I'm going to close it. 

@pgeez, if you have a moment, please leave a comment here about whether @ericdill's solution did or did not work for you so that others who find this issue can benefit from it. Thanks!
