### ISSUE TITLE
Exception: Java gateway process exited before sending its port number

### ISSUE THREAD

**Issue by yonghaihung** [jupyter/docker-stacks#884]
**What docker image you are using?**

Docker Image: `jupyter/all-spark-notebook:latest`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Docker command: 

`docker run -p 8888:8888 -p 4040:4040 --name abc -v c:\notebooks:/home/jovyan -v c:\etc\letsencrypt\live\url\privkey.pem:/etc/ssl/privkey.pem -v c:\etc\letsencrypt\live\url\fullchain.pem:/etc/ssl/fullchain.pem jupyter/all-spark-notebook start-notebook.sh --NotebookApp.keyfile=/etc/ssl/privkey.pem --NotebookApp.certfile=/etc/ssl/fullchain.pem --NotebookApp.iopub_data_rate_limit=1.0e10
`

**What steps do you take once the container is running to reproduce the issue?**

Code cell:
```
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('06MayTest')\
        .config("spark.driver.cores", "56")\
        .config("spark.driver.memory", "230g")\
        .config("spark.driver.memoryOverhead", "23g")\
        .config("spark.driver.maxResultSize", "2g")\
        .config("spark.local.dir", "/home/jovyan/tmp2/")\
        .getOrCreate()
spark.conf.set("spark.sql.shuffle.partitions", "100")
```

**What do you expect to happen?**

Was able to run above init code without issue using a tag:latest image few weeks ago. 

Restarted the instance but encountered error.

**What actually happens?**
An exception is thrown:

**Exception: Java gateway process exited before sending its port number**

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-4b0bc7caa118> in <module>
      6         .config("spark.driver.memory", "230g")\
      7         .config("spark.driver.memoryOverhead", "23g")\
----> 8         .config("spark.driver.maxResultSize", "2g")\
      9         .getOrCreate()
     10 spark.conf.set("spark.sql.shuffle.partitions", "100")

/usr/local/spark/python/pyspark/sql/session.py in getOrCreate(self)
    171                     for key, value in self._options.items():
    172                         sparkConf.set(key, value)
--> 173                     sc = SparkContext.getOrCreate(sparkConf)
    174                     # This SparkContext may be an existing one.
    175                     for key, value in self._options.items():

/usr/local/spark/python/pyspark/context.py in getOrCreate(cls, conf)
    365         with SparkContext._lock:
    366             if SparkContext._active_spark_context is None:
--> 367                 SparkContext(conf=conf or SparkConf())
    368             return SparkContext._active_spark_context
    369 

/usr/local/spark/python/pyspark/context.py in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    131                     " note this option will be removed in Spark 3.0")
    132 
--> 133         SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
    134         try:
    135             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,

/usr/local/spark/python/pyspark/context.py in _ensure_initialized(cls, instance, gateway, conf)
    314         with SparkContext._lock:
    315             if not SparkContext._gateway:
--> 316                 SparkContext._gateway = gateway or launch_gateway(conf)
    317                 SparkContext._jvm = SparkContext._gateway.jvm
    318 

/usr/local/spark/python/pyspark/java_gateway.py in launch_gateway(conf)
     44     :return: a JVM gateway
     45     """
---> 46     return _launch_gateway(conf)
     47 
     48 

/usr/local/spark/python/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise Exception("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number
```

Checked the Docker instance logs:

```
[I 02:13:30.819 NotebookApp] Replaying 10 buffered messages
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   324
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   321
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

Exception in thread "main" java.io.IOException: Failed to create a temp directory (under /tmp) after 10 attempts!
        at org.apache.spark.util.Utils$.createDirectory(Utils.scala:311)
        at org.apache.spark.util.Utils$.createTempDir(Utils.scala:332)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:335)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   407
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   404
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

Exception in thread "main" java.io.IOException: Failed to create a temp directory (under /tmp) after 10 attempts!
        at org.apache.spark.util.Utils$.createDirectory(Utils.scala:311)
        at org.apache.spark.util.Utils$.createTempDir(Utils.scala:332)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:335)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Issue is resolved after removing all instances using `docker rm <id>` and using an older tag:0d96d93393f7**

`docker run -p 8888:8888 -p 4040:4040 --name abc -v c:\notebooks:/home/jovyan -v c:\etc\letsencrypt\live\url\privkey.pem:/etc/ssl/privkey.pem -v c:\etc\letsencrypt\live\url\fullchain.pem:/etc/ssl/fullchain.pem jupyter/all-spark-notebook:0d96d93393f7 start-notebook.sh --NotebookApp.keyfile=/etc/ssl/privkey.pem --NotebookApp.certfile=/etc/ssl/fullchain.pem --NotebookApp.iopub_data_rate_limit=1.0e10
`

**Comment by parente** [comment]
> OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:

This error suggests your docker host / VM ran out of disk space. Running `docker rm <id>` probably freed up some space so that the older tag worked.

**Comment by romainx** [comment]
Hello @yonghaihung 

Any feedback on this issue?

I can confirm I'm able to run the code shared without error however with these spark settings `.config("spark.driver.memory", "230g")` you may ran into other issues unless you have a bunch of memory on the host.

Note: If we have no feedback from you, we may close this issue soon.

Best

**Comment by yonghaihung** [comment]
Hi, 

Have found the issue is due to the underlying Windows server C: drive ran out of disk space. 

The issue is resolved after changing the Disk image location under Advanced settings to another disk volume.

**Comment by romainx** [comment]
@yonghaihung thanks a lot for the quick answer :grin:.
Happy to hear that you have found the solution to your problem.

So I'm closing the issue.
Best.
