### ISSUE TITLE
Loading matplotlib fails inside of a running container

### ISSUE THREAD

**Issue by tschmel** [jupyter/docker-stacks#946]
Maybe it is not a good idea at all, but I try to use the `scipy-notebook` image to generate matplotlib plots inside a running container. While importing matplotlib inside the juypter notebook works perfectly, it is not working at when using the `(i)python` commands. Any ideas?

**What docker image you are using?**

`jupyter/scipy-notebook:17aba6048f44`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -d --name test_container  jupyter/scipy-notebook:17aba6048f44`

**What steps do you take once the container is running to reproduce the issue?**

1. Connect to the container: `docker exec -it test_container bash`
2. Start python console and import matplotlib: `python -c "import matplotlib.pyplot"`

**What do you expect to happen?**

Nothing (successful execution of the command)

**What actually happens?**

```
jovyan@015c72a57e21:~$ python -c "import matplotlib.pyplot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/opt/conda/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Comment by tschmel** [comment]
I found a possible solution [here](https://github.com/ContinuumIO/docker-images/issues/39]):

```python
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
```
