### ISSUE TITLE
Spark submission to Kubernetes API broken with Py4JJavaError

### ISSUE THREAD

**Issue by gary-lloyd** [jupyter/docker-stacks#947]
**What docker image you are using?**

`jupyter/all-spark-notebook`
Any version after `29a003bb3030`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I'm not using docker directly, instead I'm running the container in a Kubernetes cluster and trying to use the Kubernetes API to schedule Spark jobs.

Extend default service account

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: namespace
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
```

Create a deployment with something like this

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: jupyter-spark
  name: jupyter-spark
  namespace: namespace
spec:
  containers:
  - command:
    - start-notebook.sh
    - --NotebookApp.token='$(JUPYTER_TOKEN)'
    env:
    - name: JUPYTER_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: jupyter-spark
    - name: GRANT_SUDO
      value: yes
    image: jupyter/all-spark-notebook:6fb3eca57bd3
    imagePullPolicy: IfNotPresent
    name: jupyter-spark
    ports:
    - containerPort: 8888
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 128Mi
```

Expose through ingress of port forward to access the Notebook

**What steps do you take once the container is running to reproduce the issue?**

1. Open a Python Notebook
2. Run the following with appropriate values for namespace, appname and ip address

```python
import os
import pyspark
 
os.environ['PYSPARK_PYTHON'] = '/usr/bin/python3'
conf = pyspark.SparkConf()
conf.setMaster("k8s://https://kubernetes.default.svc.cluster.local:443") #k8s apiserver IP address or service
conf.set("spark.kubernetes.container.image", "gcr.io/spark-operator/spark-py:v2.4.4")
conf.set("spark.kubernetes.authenticate.caCertFile", "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt")
conf.set("spark.kubernetes.authenticate.oauthTokenFile", "/var/run/secrets/kubernetes.io/serviceaccount/token")
conf.set("spark.kubernetes.namespace","namespace")
conf.set("spark.submit.deployMode",'client')
conf.set("spark.kubernetes.pyspark.pythonVersion","3")
conf.set("spark.app.name", "spark-test")
conf.set("spark.kubernetes.executor.limit.cores", "2")
conf.set("spark.kubernetes.executor.request.cores", "0.5")
conf.set("spark.executor.memory", "2g")
conf.set("spark.executor.instances", "4")
conf.set("spark.driver.host", "ipAddress") #Hostname or IP address for the driver
conf.set("spark.driver.port", "4040")
 
#Initializing sc would spin up the Spark executor pods
sc = pyspark.SparkContext(conf=conf)
 
#Sample Spark code
rdd = sc.parallelize(range(1000000000))
rdd.sum()
```

**What do you expect to happen?**

I expect the job to complete and return the answer. This example works for `jupyter/all-spark-notebook:29a003bb3030`

**What actually happens?**

Using `jupyter/all-spark-notebook:6fb3eca57bd3` the job fails with the following stack trace
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-1-a37e483d608a> in <module>
     24 #Sample Spark code
     25 rdd = sc.parallelize(range(1000000000))
---> 26 rdd.sum()

/usr/local/spark/python/pyspark/rdd.py in sum(self)
   1044         6.0
   1045         """
-> 1046         return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
   1047 
   1048     def count(self):

/usr/local/spark/python/pyspark/rdd.py in fold(self, zeroValue, op)
    915         # zeroValue provided to each partition is unique from the one provided
    916         # to the final reduce call
--> 917         vals = self.mapPartitions(func).collect()
    918         return reduce(op, vals, zeroValue)
    919 

/usr/local/spark/python/pyspark/rdd.py in collect(self)
    814         """
    815         with SCCallSiteSync(self.context) as css:
--> 816             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    817         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    818 

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 4 times, most recent failure: Lost task 2.3 in stage 0.0 (TID 9, 10.36.0.6, executor 3): UnknownReason
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Bidek56** [comment]
I am able to run a single node Spark using Helm and the [PySpark image](https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook) on AKS/K8s but I think the preferred way to run Spark on K8s is to use the [operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator), which I believe has a [Helm chart](https://github.com/helm/charts/tree/master/incubator/sparkoperator) for it.

**Comment by Bidek56** [comment]
@gary-lloyd Have tried the latest images with Spark 3.3 on K8s? Is this still an issue? Thx

**Comment by Bidek56** [comment]
@gary-lloyd Is this still an issue? If not please close the ticket. Thx
