### ISSUE TITLE
Fail to get yarn configuration

### ISSUE THREAD

**Issue by sgbiskup** [jupyter/docker-stacks#990]
Hi 

I'm dealing with a problem which is logged as 'Fail to get yarn configuration'.
It is related to Extension Manager which can't load a list of installed extensions, neither install new extensions (tested from a terminal).
Moreover, when I try to check nodejs and npm installed versions I receive below results
```
jovyan@jupyter-datascience-notebook1:~$ node -v
v12.4.0
jovyan@jupyter-datascience-notebook1:~$ npm -v
Segmentation fault (core dumped)
```

What is strange is that docker container run locally doesn't generate such error, but a container that is run on remote Synology NAS server. Maybe there's need to manually configure IP address inside the container on NAS. 

**Docker image:**

`jupyter/jupyter-datascience-notebook`  
`jupyter/jupyter-all-spark-notebook`

**Running container command:**

Default `docker run` command from `README.md` with additional envirnoment params  
`JUPYTER_ENABLE_LAB=yes`  
`GRANT_SUDO=yes`  
`GEN_CERT=yes`  

**Steps to reproduce the issue?**

1. Visit http://192.168.1.10:8888  
2.1. Enter Extension Manager
2.2. `npm -v` in terminal

**What do you expect to happen?**

See extensions list

**What actually happens?**  

Output from web browser:
```
Error communicating with server extension. Consult the documentation for how to ensure that it is enabled.  
Reason given:  
Error: 500 (Internal Server Error)
```

Output from logs:  
```
[E 14:33:39.704 LabApp] 500 GET /lab/api/extensions?1579962715305 (172.17.0.1) 4611.93ms referer=https://192.168.1.10:8888/lab?
[E 14:33:39.705 LabApp] Uncaught exception GET /lab/api/extensions?1579962715340 (172.17.0.1)
    HTTPServerRequest(protocol='https', host='192.168.1.10:8888', method='GET', uri='/lab/api/extensions?1579962715340', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 92, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 161, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 195, in _load_outdated
        app_options=self.app_options
      File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 550, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1675, in latest_compatible_package_versions
        raise ValueError(msg % keys)
    ValueError: "['@jupyter-widgets/jupyterlab-manager@1.1.0', 'jupyterlab_bokeh@1.0.0']" is not a valid npm package
```

**Comment by sgbiskup** [comment]
Actually problem solved by the latest build from dockerhub

jupyter/all-spark-notebook:437f1ef92733

**Comment by danlester** [comment]
I find something similar, and even in the latest (2fd856878b83) build of minimal-notebook I have to upgrade conda before the node problems go away.

E.g. for:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

I see:
```
Fail to get yarn configuration. /opt/conda/bin/node: /opt/conda/bin/../lib/libcrypto.so.1.1: version 'OPENSSL_1_1_1b' not found (required by /opt/conda/bin/node)
```

Running any conda command I get the upgrade notice:

> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.7.12
>   latest version: 4.8.2
> 
> Please update conda by running
> 
>     $ conda update -n base conda


Once I run that, the earlier command now works correctly and the JupyterLab build runs.

**Comment by gitclem** [comment]
When I try to run:

jupyter labextension install @jupyter-widgets/jupyterlab-manager

I get the error:

```
Fail to get yarn configuration. /home/clem/BUILD/Python-3.7.11/3.7-env/lib/python3.7/site-packages/jupyterlab/staging/yarn.js:1175
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Fail to get yarn configuration. /home/clem/BUILD/Python-3.7.11/3.7-env/lib/python3.7/site-packages/jupyterlab/staging/yarn.js:1175
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-34zxzqet.log
```

I tried replacing the offending line with:

`  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir) {
`

but I run into another error:


```
Fail to get yarn configuration. /home/clem/BUILD/Python-3.7.11/3.7-env/lib/python3.7/site-packages/jupyterlab/staging/yarn.js:1347
  var _ref36 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (paths, mode = constants.W_OK | constants.X_OK) {
                                                                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

I'm on on:

* Ubuntu 16.04 LTS
* Python 3.11
* node v4.2.6

And when I run

```
jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.1
ipython          : 7.25.0
ipykernel        : 6.0.1
jupyter client   : 6.1.12
Fail to get yarn configuration. /home/clem/BUILD/Python-3.7.11/3.7-env/lib/python3.7/site-packages/jupyterlab/staging/yarn.js:1347
  var _ref36 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (paths, mode = constants.W_OK | constants.X_OK) {

jupyter lab      : 3.0.16
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```
I'm in the weeds, as I don't really understand what's going on....

**Comment by mathbunnyru** [comment]
Please, create a new issue if you have some errors. And please use issue template to make it easy for maintainers.
